'use strict';
(()=>{
const sim=window.sim,renderer=window.renderer,AZ=window.AZ,W=AZ?.WorldV9;if(!sim||!renderer||!W)return;const O=W.OCC,C=W.CELL,G=W.GRID;
const baseRender=renderer.render.bind(renderer);
const colors={road:'#454b47',water:'#274b50',dense:'#1b2f22',rubble:'#665e55',wall:'#252b28',door:'#76543a',window:'#557e8b',furniture:'#4b4237'};
function runs(c){if(c.preview)return[];if(c._v9Runs)return c._v9Runs;const out=[];for(let y=0;y<G;y++){let start=0,code=c.occ[y*G];for(let x=1;x<=G;x++){const n=x<G?c.occ[y*G+x]:-1;if(n!==code){if([O.ROAD,O.WATER,O.DENSE,O.RUBBLE].includes(code))out.push({y,x:start,n:x-start,code});start=x;code=n}}}return c._v9Runs=out}
function cellRect(ctx,c,x,y,code){const wx=c.cx*AZ.CHUNK_SIZE+x*C,wy=c.cy*AZ.CHUNK_SIZE+y*C;if(code===O.WALL){ctx.fillStyle=colors.wall;ctx.fillRect(wx,wy,C,C)}else if(code===O.DOOR_CLOSED||code===O.DOOR_OPEN){ctx.fillStyle=colors.door;ctx.fillRect(wx+4,wy+2,C-8,C-4);if(code===O.DOOR_OPEN){ctx.strokeStyle='rgba(220,190,145,.7)';ctx.beginPath();ctx.moveTo(wx+3,wy+3);ctx.lineTo(wx+C-3,wy+C-3);ctx.stroke()}}else if(code===O.WINDOW){ctx.fillStyle=colors.window;ctx.fillRect(wx+3,wy+5,C-6,6)}else if(code===O.FURNITURE){ctx.fillStyle=colors.furniture;ctx.fillRect(wx+3,wy+3,C-6,C-6)}else if(code===O.RUBBLE){ctx.fillStyle=colors.rubble;ctx.fillRect(wx+2,wy+4,C-4,C-8)}}
renderer.drawChunk=function(c){const ctx=this.ctx,cs=AZ.CHUNK_SIZE,x=c.cx*cs,y=c.cy*cs;ctx.fillStyle=c.biome==='forest'?'#233526':c.biome==='farmland'?'#3a432b':c.biome==='marsh'?'#243b38':'#2e3b2e';ctx.fillRect(x,y,cs+1,cs+1);if(c.preview){ctx.fillStyle=colors.road;if(c.roads?.vertical)ctx.fillRect(x+cs/2-30,y,60,cs);if(c.roads?.horizontal)ctx.fillRect(x,y+cs/2-30,cs,60);if(this.sim.overlays.rad&&this.drawRadChunk)this.drawRadChunk(c);return}for(const r of runs(c)){ctx.fillStyle=r.code===O.ROAD?colors.road:r.code===O.WATER?colors.water:r.code===O.DENSE?colors.dense:colors.rubble;ctx.fillRect(x+r.x*C,y+r.y*C,r.n*C,C)}
 if(this.sim.camera.zoom<.38){for(const s of c.sites){ctx.fillStyle=s.type==='power_plant'?'#4c5550':s.type==='warehouse'?'#665f52':'#655846';ctx.fillRect(s.x,s.y,s.w,s.h)}if(this.sim.overlays.rad&&this.drawRadChunk)this.drawRadChunk(c);return}
 for(const s of c.sites){ctx.fillStyle='rgba(132,113,82,.24)';ctx.fillRect(s.x,s.y,s.w,s.h);const a=W.localCell(c,s.x,s.y),x0=a.x,y0=a.y,x1=x0+Math.round(s.w/C)-1,y1=y0+Math.round(s.h/C)-1;for(let yy=y0;yy<=y1;yy++)for(let xx=x0;xx<=x1;xx++){const code=c.occ[yy*G+xx];if([O.WALL,O.DOOR_CLOSED,O.DOOR_OPEN,O.WINDOW,O.RUBBLE].includes(code)||(code===O.FURNITURE&&this.sim.camera.zoom>.72))cellRect(ctx,c,xx,yy,code)}if(this.sim.camera.zoom>.7){ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillStyle='rgba(235,236,220,.62)';ctx.fillText(s.name,s.x+s.w/2,s.y-5)}if(this.sim.camera.zoom>.95)for(const co of s.containers||[]){ctx.fillStyle=co.searched?'#62594a':'#8a724d';ctx.fillRect(co.x-4,co.y-4,8,8)}}if(this.sim.overlays.rad&&this.drawRadChunk)this.drawRadChunk(c)};
renderer.pick=function(sx,sy){const w=this.screenToWorld(sx,sy),rad=30/this.sim.camera.zoom,rad2=rad*rad,world=this.sim.world;let best=null,bd=rad2;const consider=e=>{if(!e)return;const ex=e.x+(e.w||0)/2,ey=e.y+(e.h||0)/2,d=(ex-w.x)**2+(ey-w.y)**2;if(d<bd){bd=d;best=e}};const ppl=this.sim.peopleGrid?.near?this.sim.peopleGrid.near(w.x,w.y,rad):this.sim.people;for(const p of ppl)if(p.alive)consider(p);const zs=this.sim.zombieGrid?.near?this.sim.zombieGrid.near(w.x,w.y,rad):this.sim.zombies;for(const z of zs)if(z.alive)consider(z);let site=world.siteAtLoaded?.(w.x,w.y)||null;if(!best&&site&&this.sim.camera.zoom>=.72){let local=null,ld=(18/this.sim.camera.zoom)**2;for(const e of [...(site.containers||[]),...(site.doors||[]),...(site.windows||[])]){const d=(e.x-w.x)**2+(e.y-w.y)**2;if(d<ld){ld=d;local=e}}if(local)best=local}if(!best){for(const c of world.chunks?.values?.()||[])for(const v of c.vehicles||[]){const d=(v.x-w.x)**2+(v.y-w.y)**2;if(d<bd){bd=d;best=v}}}if(!best&&site)best=site;if(!best)for(const s of this.sim.structures||[]){const d=(s.x-w.x)**2+(s.y-w.y)**2;if(d<(28/this.sim.camera.zoom)**2){best=s;break}}if(!best&&!world.peekChunk?.(AZ.chunkCoord(w.x),AZ.chunkCoord(w.y)))world.requestChunk?.(AZ.chunkCoord(w.x),AZ.chunkCoord(w.y),8,'user-pick');this.sim.selected=best;window.dispatchEvent(new CustomEvent('az-selection',{detail:best}))};
renderer.render=function(){baseRender();const light=sim.world.lightAt(sim.minute);if(light>=.78)return;const ctx=this.ctx,w=this.canvas.width/this.dpr,h=this.canvas.height/this.dpr,alpha=(1-light)*.56;ctx.save();ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.fillStyle=`rgba(4,7,8,${alpha})`;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='destination-out';const lights=[];for(const s of sim.structures||[])if(s.type==='campfire'&&s.integrity>0&&this.inView(s.x,s.y,120))lights.push({x:s.x,y:s.y,r:95});for(const p of sim.people)if(p.alive&&this.inView(p.x,p.y,100)&&sim.itemQty(p,'torch')>0)lights.push({x:p.x,y:p.y,r:70});for(const l of lights){const sx=w/2+(l.x-sim.camera.x)*sim.camera.zoom,sy=h/2+(l.y-sim.camera.y)*sim.camera.zoom,rr=l.r*sim.camera.zoom,g=ctx.createRadialGradient(sx,sy,0,sx,sy,rr);g.addColorStop(0,'rgba(0,0,0,.92)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(sx,sy,rr,0,Math.PI*2);ctx.fill()}ctx.restore()};
})();
