'use strict';
(()=>{
const sim=window.sim,$=id=>document.getElementById(id);if(!sim||!$('inspectPanel'))return;const ver=document.querySelector('.drawerHead small');if(ver)ver.textContent='v0.10.1 · performance estrutural + estabilidade';const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let panel=$('worldInspectorV9');if(!panel){panel=document.createElement('div');panel.id='worldInspectorV9';panel.className='v9worldInspect hidden';$('inspector').insertAdjacentElement('afterend',panel);const st=document.createElement('style');st.textContent='.v9worldInspect{margin-top:12px}.v9worldInspect.hidden{display:none}.v9worldInspect .v9box{padding:9px;margin:6px 0;border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.035);border-radius:9px}.v9worldInspect small{display:block;opacity:.68;line-height:1.45}.v9pill{display:inline-block;padding:3px 6px;margin:2px;border-radius:6px;background:rgba(255,255,255,.06);font-size:10px}';document.head.appendChild(st)}
function siteView(s){const containers=s.containers||[],doors=s.doors||[],windows=s.windows||[],searched=containers.filter(c=>c.searched).length,open=doors.filter(d=>d.open).length;return`<h3>Mundo físico</h3><div class="v9box"><b>${esc(s.name)}</b><small>${esc(s.type)} · ${s.rooms?.length||0} cômodos · ${doors.length} portas · ${windows.length} janelas</small></div><div class="v9box"><b>Recipientes</b><small>${searched}/${containers.length} já revistados</small>${containers.map(c=>`<span class="v9pill">${esc(c.name)} · ${c.locked?'trancado':c.searched?'revistado':'não revistado'}</span>`).join('')}</div><div class="v9box"><b>Aberturas</b><small>${open} portas abertas</small>${[...doors,...windows].map(o=>`<span class="v9pill">${esc(o.openingType)} · ${o.open?'aberta':o.locked?'trancada':(o.barricade||0)>0?'barricada':'fechada'}</span>`).join('')}</div>`}
function containerView(c){const visible=c.searched?(c.loot||[]).filter(i=>i.qty>0):[];return`<h3>Recipiente</h3><div class="v9box"><b>${esc(c.name)}</b><small>${c.locked?'trancado · ':''}${c.searched?'já foi revistado':'conteúdo ainda não conhecido por busca'}</small>${c.searched?(visible.length?visible.map(i=>`<span class="v9pill">${esc(i.name)} ×${i.qty}</span>`).join(''):'<small>vazio</small>'):''}</div>`}
function openingView(o){return`<h3>Abertura</h3><div class="v9box"><b>${esc(o.openingType==='window'?'Janela':'Porta')}</b><small>${o.open?'aberta':o.locked?'trancada':'fechada'} · integridade ${Math.round(o.integrity||0)} · barricada ${Math.round((o.barricade||0)*100)}%</small></div>`}
function inspectVisible(){return $('drawer')?.classList.contains('open')&&document.querySelector('[data-tab="inspect"]')?.classList.contains('active')}
function render(){const o=sim.selected;if(!o||!['site','container','opening'].includes(o.kind)){panel.classList.add('hidden');return}panel.classList.remove('hidden');const html=o.kind==='site'?siteView(o):o.kind==='container'?containerView(o):openingView(o);if(panel.innerHTML!==html)panel.innerHTML=html}
window.addEventListener('az-selection',render);setInterval(()=>{if(!document.hidden&&inspectVisible())render()},900);render();const world=$('worldtabPanel');if(world&&!$('v9WorldStats')){const box=document.createElement('div');box.id='v9WorldStats';box.className='meterBlock';box.innerHTML='<div><span>Grade</span><b>16 px</b></div><div><span>Busca recipientes</span><b id="v9Searches">0</b></div><div><span>Itens retirados</span><b id="v9Items">0</b></div><div><span>Repaths</span><b id="v9Paths">0</b></div>';world.prepend(box);setInterval(()=>{if(document.hidden||!document.querySelector('[data-tab="worldtab"]')?.classList.contains('active'))return;if($('v9Searches'))$('v9Searches').textContent=sim.world.regionStats.containersSearched;if($('v9Items'))$('v9Items').textContent=sim.world.regionStats.itemsRemoved;if($('v9Paths'))$('v9Paths').textContent=sim._v9?.pathReplans||0},1100)}
})();
