'use strict';
(()=>{
const sim=window.sim;if(!sim?.ai)return;const ai=sim.ai;
ai.requests=ai.requests||0;ai.promptTokens=ai.promptTokens||0;ai.completionTokens=ai.completionTokens||0;ai.reasoningTokens=ai.reasoningTokens||0;ai.cachedTokens=ai.cachedTokens||0;ai.cost=ai.cost||0;ai.fallbacks=ai.fallbacks||0;ai.totalLatency=ai.totalLatency||0;ai.controllers=new Map();ai.byModel=ai.byModel||{};ai.byAgent=ai.byAgent||{};ai.account={credits:null,key:null,lastSync:0,error:''};
ai.managementKey=localStorage.getItem('az_management_key')||'';const oldFree='google/gemma-4-26b-a4b-it:free';if(!ai.lightModel||ai.lightModel===oldFree){ai.lightModel='openai/gpt-oss-20b';localStorage.setItem('az_light_model',ai.lightModel)}if(!ai.deepModel)ai.deepModel='openai/gpt-oss-20b';
ai.saveSettings=function(key,managementKey,light,deep,enabled){this.apiKey=(key||'').trim();this.managementKey=(managementKey||'').trim();this.lightModel=(light||'openai/gpt-oss-20b').trim();this.deepModel=(deep||'openai/gpt-oss-20b').trim();this.enabled=!!enabled;if(this.apiKey)localStorage.setItem('az_openrouter_key',this.apiKey);else localStorage.removeItem('az_openrouter_key');if(this.managementKey)localStorage.setItem('az_management_key',this.managementKey);else localStorage.removeItem('az_management_key');localStorage.setItem('az_light_model',this.lightModel);localStorage.setItem('az_deep_model',this.deepModel);localStorage.setItem('az_ai_enabled',this.enabled?'1':'0')};
ai.decide=function(agent,deep=false,trigger='routine'){if(!this.enabled||!this.apiKey||!agent.alive||agent.brain.pending)return false;agent.brain.pending=true;agent.brain.pendingSince=performance.now();this.activeBrains.add(agent.id);this.request({agent,deep,trigger}).finally(()=>{agent.brain.pending=false;agent.brain.pendingSince=0;this.activeBrains.delete(agent.id);this.controllers.delete(agent.id)});return true};
ai.fetchCompletion=async function(body,agentId,timeoutMs=18000){const ctrl=new AbortController();this.controllers.set(agentId,ctrl);const timer=setTimeout(()=>ctrl.abort(),timeoutMs),started=performance.now();this.requests++;try{const res=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal:ctrl.signal,headers:{Authorization:`Bearer ${this.apiKey}`,'Content-Type':'application/json','HTTP-Referer':location.origin+location.pathname,'X-Title':'Ashfall County'},body:JSON.stringify(body)});this.totalLatency+=performance.now()-started;if(!res.ok){const e=new Error(`OpenRouter ${res.status}: ${await res.text()}`);e.status=res.status;throw e}return await res.json()}catch(err){if(err?.name==='AbortError'){const e=new Error('OpenRouter timeout: cérebro não respondeu em 18s');e.status=408;throw e}throw err}finally{clearTimeout(timer)}};
ai.accountUsage=function(u={},model,agent){const prompt=u.prompt_tokens||0,completion=u.completion_tokens||0,total=u.total_tokens||(prompt+completion),reason=u.completion_tokens_details?.reasoning_tokens||0,cached=u.prompt_tokens_details?.cached_tokens||0,cost=Number(u.cost||0)||0;this.tokens+=total;this.promptTokens+=prompt;this.completionTokens+=completion;this.reasoningTokens+=reason;this.cachedTokens+=cached;this.cost+=cost;const m=this.byModel[model]||(this.byModel[model]={calls:0,tokens:0,cost:0});m.calls++;m.tokens+=total;m.cost+=cost;const a=this.byAgent[agent.id]||(this.byAgent[agent.id]={name:agent.name,calls:0,tokens:0,cost:0});a.calls++;a.tokens+=total;a.cost+=cost};
})();
