'use strict';
(()=>{
const sim=window.sim,$=id=>document.getElementById(id);if(!sim?.ai||!$('aiPanel'))return;const ai=sim.ai;const tabs=document.querySelector('.tabs');if(tabs&&!document.querySelector('[data-tab="aimetrics"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='aimetrics';b.textContent='Uso IA';tabs.insertBefore(b,document.querySelector('[data-tab="worldtab"]'));b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('aimetricsPanel').classList.add('active');refresh()}}
if(!$('managementKey')){const l=document.createElement('label');l.innerHTML='Management Key<input id="managementKey" class="field" type="password" placeholder="chave de gerenciamento" autocomplete="off">';$('apiKey').closest('label').after(l)}$('managementKey').value=ai.managementKey||'';$('lightModel').value=ai.lightModel;$('deepModel').value=ai.deepModel;const label=[...$('aiPanel').querySelectorAll('.meterBlock span')].find(x=>x.textContent==='Cérebros ativos');if(label)label.textContent='Cérebros processando';
if(!$('aimetricsPanel')){const sec=document.createElement('section');sec.className='panel';sec.id='aimetricsPanel';sec.innerHTML='<div class="row"><button id="refreshAiMetrics" class="primary">Atualizar métricas</button><span id="aiMetricsStatus" class="hint">não sincronizado</span></div><div class="metricHero"><small>SALDO OPENROUTER</small><b id="orBalance">—</b></div><div id="aiMetricGrid" class="meterBlock"></div><h3>Por modelo</h3><div id="aiByModel" class="metricList"></div><h3>Por agente</h3><div id="aiByAgent" class="metricList"></div><p class="hint">Sem teto interno de créditos. Management Key consulta saldo; API Key executa os cérebros.</p>';$('worldtabPanel').before(sec);$('refreshAiMetrics').onclick=refresh}
const css=document.createElement('style');css.textContent='.metricHero{margin:12px 0;padding:14px;border:1px solid rgba(128,190,220,.22);border-radius:12px;background:rgba(35,67,82,.16)}.metricHero small{display:block;opacity:.65;font-size:10px}.metricHero b{display:block;font-size:24px;margin-top:4px}.metricList{display:grid;gap:6px}.metricRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:8px;background:rgba(255,255,255,.035);border-radius:8px}.metricRow span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.metricRow b{font-size:10px}';document.head.appendChild(css);
const money=v=>Number.isFinite(+v)?`US$ ${(+v).toFixed(6).replace(/0+$/,'').replace(/\.$/,'')}`:'—',compact=v=>Intl.NumberFormat('pt-BR',{notation:'compact'}).format(v||0),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){const cr=ai.account?.credits,k=ai.account?.key,bal=cr?Number(cr.total_credits||0)-Number(cr.total_usage||0):NaN;$('orBalance').textContent=Number.isFinite(bal)?money(bal):'—';$('aiMetricGrid').innerHTML=[['Custo sessão',money(ai.cost)],['Requests',ai.requests],['Sucessos',ai.calls],['Falhas',ai.fails],['Retries',ai.fallbacks],['Input',compact(ai.promptTokens)],['Output',compact(ai.completionTokens)],['Reasoning',compact(ai.reasoningTokens)],['Cached',compact(ai.cachedTokens)],['Latência',`${Math.round(ai.totalLatency/Math.max(1,ai.requests))} ms`],['Uso key',k?money(k.usage):'—'],['Uso hoje',k?money(k.usage_daily):'—'],['Uso mensal',k?money(k.usage_monthly):'—'],['Limite key',k?(k.limit==null?'sem limite':money(k.limit)):'—']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('aiByModel').innerHTML=Object.entries(ai.byModel).sort((a,b)=>b[1].cost-a[1].cost).map(([n,v])=>`<div class="metricRow"><span>${esc(n)}</span><b>${v.calls} · ${compact(v.tokens)} tok · ${money(v.cost)}</b></div>`).join('')||'<span class="hint">Sem uso.</span>';$('aiByAgent').innerHTML=Object.values(ai.byAgent).sort((a,b)=>b.cost-a.cost).map(v=>`<div class="metricRow"><span>${esc(v.name)}</span><b>${v.calls} · ${compact(v.tokens)} tok · ${money(v.cost)}</b></div>`).join('')||'<span class="hint">Sem uso.</span>'}
async function refresh(){const st=$('aiMetricsStatus');if(st)st.textContent='sincronizando...';const r=await ai.refreshAccountMetrics();if(st)st.textContent=r.error?`erro: ${r.error}`:`atualizado ${new Date(r.lastSync).toLocaleTimeString()}`;render()}
$('saveKey').onclick=async()=>{ai.saveSettings($('apiKey').value,$('managementKey').value,$('lightModel').value,$('deepModel').value,$('aiEnabled').checked);for(const p of sim.people)if(p.type==='agent'){p.brain.retryAfter=0;p.brain.pending=false;p.brain.nextDecision=Math.min(p.brain.nextDecision,sim.minute+.02)}await refresh()};$('clearKey').onclick=()=>{ai.saveSettings('','',$('lightModel').value,$('deepModel').value,$('aiEnabled').checked);$('apiKey').value='';$('managementKey').value=''};$('aiEnabled').onchange=e=>ai.saveSettings($('apiKey').value,$('managementKey').value,$('lightModel').value,$('deepModel').value,e.target.checked);setInterval(render,1000);if(ai.apiKey||ai.managementKey)refresh();
})();
