'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ,V=window.AZV8;if(!sim||!AZ||!V||!sim.applyBrainIntent||!V.maintainIntent)return;
const direction=(dx,dy)=>['E','SE','S','SW','W','NW','N','NE'][(Math.round(Math.atan2(dy,dx)/(Math.PI/4))+8)%8];
if(!AZ.AGENT_TOOLS.some(t=>t.function?.name==='continue'))AZ.AGENT_TOOLS.push({type:'function',function:{name:'continue',description:'Manter a intenção atual sem inventar uma nova ação. Use quando o plano em andamento continua adequado.',parameters:{type:'object',properties:{reason:{type:'string'}},required:['reason'],additionalProperties:false}}});
const oldApply=sim.applyBrainIntent.bind(sim),oldMaintain=V.maintainIntent,aiDecide=sim.ai?.decide?.bind(sim.ai);
function state(p){return p._v12exec||(p._v12exec={accepted:0,started:0,rejected:0,local:0,stall:0,lastTool:'',lastError:'',lastAcceptedMinute:-1,lastStartedMinute:-1})}
function rememberFailure(p,tool,why){const s=state(p);s.rejected++;s.lastError=why;p.brain.lastExecutionError=why;sim.remember?.(p,'decision',`A intenção ${tool} não pôde ser executada: ${why}`,4,['decision','execution']);V.markReplan?.(p,'intent_execution_failed',false)}
function nearestThreat(p,r=150){const zs=sim.zombieGrid?.near?.(p.x,p.y,r)||[];let best=null,bd=Infinity;for(const z of zs){if(!z.alive)continue;const d=(z.x-p.x)**2+(z.y-p.y)**2;if(d<bd){bd=d;best=z}}return best?{z:best,d:Math.sqrt(bd)}:null}
function loadedSiteWith(p,item,r=430){const sites=sim.world.nearbySites?.(p.x,p.y,r)||[];let best=null,bd=Infinity;for(const s of sites){if(s.fire>0)continue;const has=(s.loot||[]).some(i=>i.qty>0&&(!item||i.id===item));if(!has)continue;const x=s.x+s.w/2,y=s.y+s.h/2,d=(x-p.x)**2+(y-p.y)**2;if(d<bd){bd=d;best=s}}return best}
function utility(p){if(!p?.alive||p.type!=='agent')return null;const b=p.brain,it=b.intent;if(it&&!it.bridge)return null;const t=nearestThreat(p,130);if(t){const armed=!!p.equippedWeapon&&p.energy>20&&p.health>48;if(armed&&t.d<Math.max(55,sim.weaponStats(p).range*.9))return{tool:'attack',args:{target_id:t.z.id,style:p.energy>55?'balanced':'quick',reason:'há uma ameaça imediata ao meu alcance'},urgent:true};const dx=p.x-t.z.x,dy=p.y-t.z.y;return{tool:'flee',args:{threat_id:t.z.id,direction:direction(dx,dy),reason:'preciso abrir distância desta ameaça agora'},urgent:true}}
 if(p.bleeding>1.25&&sim.itemQty(p,'bandage'))return{tool:'consume',args:{item_id:'bandage',reason:'preciso conter o sangramento'},urgent:true};
 if(p.thirst>72&&sim.itemQty(p,'water'))return{tool:'consume',args:{item_id:'water',reason:'estou com sede e já carrego água'}};
 if(p.hunger>76&&sim.itemQty(p,'food'))return{tool:'consume',args:{item_id:'food',reason:'estou com fome e já carrego alimento'}};
 if((p.bodyClock?.sleepPressure||0)>88&&sim.currentSite?.(p))return{tool:'rest',args:{hours:1,reason:'estou exausto e encontrei abrigo'}};
 if(p.thirst>72&&!sim.itemQty(p,'water')){const s=loadedSiteWith(p,'water');if(s)return{tool:'scavenge',args:{site_id:s.id,wanted:'water',reason:'preciso procurar água neste local próximo'}}}
 if(p.hunger>76&&!sim.itemQty(p,'food')){const s=loadedSiteWith(p,'food');if(s)return{tool:'scavenge',args:{site_id:s.id,wanted:'food',reason:'preciso procurar alimento neste local próximo'}}}
 return null;
}
function applyLocal(p,d){if(!d)return false;const s=state(p),ok=oldApply(p,d.tool,d.args,{event:{reason:'local_utility',urgent:!!d.urgent},model:'local-utility',local:true});if(ok){s.local++;p.brain.lastThought=d.args.reason||p.brain.lastThought;p.brain.lastModel='local-utility';p.brain.replanPending=null;oldMaintain(p)}return ok}
function confirm(p,tool,beforeIntent,beforeAction){const s=state(p);if(p.action&&p.action!==beforeAction){s.started++;s.stall=0;s.lastStartedMinute=sim.minute;p.brain.lastExecutionError='';return true}if(p.brain.nextIntent&&p.brain.nextIntent!==beforeIntent){s.stall=0;return true}const it=p.brain.intent;if(it&&it.tool===tool){oldMaintain(p);if(p.action){s.started++;s.stall=0;s.lastStartedMinute=sim.minute;p.brain.lastExecutionError='';return true}if(['wait','set_goal','continue'].includes(tool)||it.completedOnce){s.stall=0;return true}}
 if(tool==='continue'){s.stall=0;return true}s.stall++;if(s.stall>=2){rememberFailure(p,tool,'o corpo não conseguiu iniciar nenhuma ação compatível');s.stall=0}return false}
sim.applyBrainIntent=function(p,tool,args={},meta={}){if(!p?.alive||p.type!=='agent')return false;const s=state(p);if(tool==='continue'){s.accepted++;s.lastTool=tool;s.lastAcceptedMinute=sim.minute;p.brain.lastThought=String(args.reason||'Vou manter o plano atual.');p.brain.lastExecutionError='';p.brain.replanPending=null;if(!p.brain.intent)applyLocal(p,utility(p));else oldMaintain(p);return true}const beforeIntent=p.brain.intent,beforeAction=p.action,ok=oldApply(p,tool,args,meta);if(!ok){rememberFailure(p,tool,'a intenção foi rejeitada pelo motor');return false}s.accepted++;s.lastTool=tool;s.lastAcceptedMinute=sim.minute;p.brain.lastExecutionError='';confirm(p,tool,beforeIntent,beforeAction);return true};
V.maintainIntent=function(p){if(!p?.alive||p.type!=='agent')return oldMaintain(p);if(!p.action){const d=utility(p);if(d)applyLocal(p,d)}oldMaintain(p);const s=state(p),it=p.brain.intent;if(!p.action&&it&&!it.bridge&&!['set_goal','continue'].includes(it.tool)){s.stall++;if(s.stall>=3){rememberFailure(p,it.tool,'a intenção persistiu sem gerar ação física');p.brain.intent=null;s.stall=0;const d=utility(p);if(d)applyLocal(p,d)}}else if(p.action)s.stall=0};
const strategic=/initial_plan|first_|unexplained|witnessed_death|conversation|speech|promise|betray|rupture|group|trade_counteroffer|novelty_accumulated|intent_execution_failed|leadership|identity/i;
if(aiDecide)sim.ai.decide=function(agent,deep=false,event={reason:'replan',urgent:false}){const d=utility(agent);if(d&&!event?.urgent){applyLocal(agent,d);return false}const reason=String(event?.reason||'');if(!event?.urgent&&!strategic.test(reason)){agent.brain.replanPending=null;return false}return aiDecide(agent,deep,event)};
const oldSelect=sim.ai?.selectTools?.bind(sim.ai);if(oldSelect)sim.ai.selectTools=function(trigger,a){const tools=oldSelect(trigger,a)||[],names=new Set(tools.map(t=>t.function?.name));for(const n of['wait','continue']){const t=AZ.AGENT_TOOLS.find(x=>x.function?.name===n);if(t&&!names.has(n))tools.push(t)}return tools};
sim.executionStats=()=>{let accepted=0,started=0,rejected=0,local=0;for(const p of sim.people){const s=p._v12exec;if(!s)continue;accepted+=s.accepted;started+=s.started;rejected+=s.rejected;local+=s.local}return{accepted,started,rejected,local}};
})();
