'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ,V=window.AZV8;if(!sim||!AZ||!V)return;const clamp=AZ.clamp;
const P={fists:{family:'unarmed',trauma:'blunt',reach:32,control:.32,knock:.34,noise:.12},kitchen_knife:{family:'blade',trauma:'cut',reach:37,control:.46,knock:.12,noise:.11},improvised_knife:{family:'blade',trauma:'cut',reach:36,control:.38,knock:.12,noise:.12},baton:{family:'blunt',trauma:'blunt',reach:43,control:.62,knock:.62,noise:.18},wooden_club:{family:'blunt',trauma:'blunt',reach:45,control:.46,knock:.7,noise:.2},crowbar:{family:'blunt',trauma:'blunt',reach:48,control:.5,knock:.78,noise:.21},tire_iron:{family:'blunt',trauma:'blunt',reach:45,control:.5,knock:.72,noise:.2},axe:{family:'blade',trauma:'chop',reach:50,control:.36,knock:.75,noise:.24},spear:{family:'spear',trauma:'puncture',reach:78,control:.7,knock:.34,noise:.15},pistol:{family:'firearm',trauma:'gunshot',reach:245,control:.56,knock:.16,noise:1.15},service_rifle:{family:'firearm',trauma:'gunshot',reach:430,control:.76,knock:.22,noise:1.35}};
const STYLE={quick:{acc:.08,dmg:.76,energy:.75,time:.72,guard:.08},balanced:{acc:0,dmg:1,energy:1,time:1,guard:.14},heavy:{acc:-.11,dmg:1.48,energy:1.5,time:1.42,guard:-.08},push:{acc:.08,dmg:.12,energy:.82,time:.8,guard:.28},aimed:{acc:.2,dmg:1.12,energy:.9,time:1.5,guard:.02},defensive:{acc:.02,dmg:.7,energy:.8,time:.92,guard:.48},stomp:{acc:.16,dmg:1.65,energy:1.25,time:1.22,guard:-.1}};
function ensure(e){if(!e)return null;e.combat=e.combat||{stance:'balanced',balance:100,guard:0,recoil:0,knockedUntil:0,grabbedBy:null,grabbedUntil:0,lastAttack:-999,lastHit:-999,weaponCondition:{},impulse:null};e.combat.weaponCondition=e.combat.weaponCondition||{};return e.combat}
function profile(p){const w=sim.weaponStats(p),x=P[w.id]||P.fists;return{...w,...x,reach:x.reach||w.range||34}}
function crowd(t,attacker){let n=0;for(const z of sim.zombieGrid.near(t.x,t.y,58))if(z.alive&&z.id!==attacker?.id)n++;return n}
function woundPenalty(p){return clamp((p.pain||0)/150+(100-(p.energy||100))/230+(p.bleeding||0)/18+(p.bodyClock?.sleepPressure||0)/280,0,.8)}
function zone(attacker,target,style,isGun){let r=sim.rng.next(),head=isGun?.13:.08;if(style==='aimed')head+=isGun?.24:.1;if(target.kind==='zombie'&&sim.skillLevel(attacker,isGun?'shooting':profile(attacker).skill)>5)head+=.05;if(r<head)return'cabeça';r=(r-head)/(1-head);if(r<.5)return'torso';if(r<.75)return'braço';return'perna'}
function traumaName(p,z){if(p.trauma==='gunshot')return`ferimento por projétil em ${z}`;if(p.trauma==='cut'||p.trauma==='chop')return`laceração em ${z}`;if(p.trauma==='puncture')return`perfuração em ${z}`;return`trauma contuso em ${z}`}
function impulse(attacker,target,style,damage,w){if(!target?.alive||style==='stomp')return;const dx=target.x-attacker.x,dy=target.y-attacker.y,l=Math.hypot(dx,dy)||1;let speed=(style==='push'?150:style==='heavy'?92:style==='quick'?42:62)*(w.family==='blunt'?1.12:w.family==='firearm'?.45:w.family==='blade'||w.family==='spear'?.82:1);speed*=clamp((damage||8)/16,.55,1.25);ensure(target).impulse={vx:dx/l*speed,vy:dy/l*speed}}
function credit(p,t,method='combat'){if(!p||!t||t._killCredited)return;t._killCredited=true;V.ensurePerson(p);p.stats.kills++;if(t.kind==='zombie')p.stats.zombieKills++;else if(t.kind==='person')p.stats.humanKills++;if(method==='vehicle')p.stats.vehicleKills++;sim.remember(p,'kill',`Matou ${t.kind==='zombie'?'uma ameaça':'uma pessoa'} usando ${method==='vehicle'?'um veículo':'combate'}.`,8,['combat','kill']);}
function humanTrauma(a,t,dmg,w,z){const mult=z==='cabeça'?1.35:z==='perna'?.86:z==='braço'?.78:1,final=Math.max(1,dmg*mult),sev=clamp(final/45,.08,1),bleed=w.trauma==='gunshot'?sev*1.35:(w.trauma==='cut'||w.trauma==='chop'||w.trauma==='puncture')?sev*.9:sev*.18;t.health-=final;t.pain=clamp(t.pain+final*.42,0,100);t.wounds.push({type:traumaName(w,z),zone:z,severity:sev,infected:false,bleeding,minute:sim.minute,source:a.id});ensure(t).balance=clamp(ensure(t).balance-final*(z==='perna'?1.25:.55),0,100);const sa=V.social(t,a),sb=V.social(a,t);sa.affinity=-100;sa.trust=-100;sa.fear=clamp(sa.fear+45,0,100);sb.affinity=clamp(sb.affinity-35,-100,100);t.relations?.set(a.id,-100);a.relations?.set(t.id,clamp((a.relations.get(t.id)||0)-35,-100,100));return final}
function start(a,id,style='balanced',meta={}){const t=sim.entityById(id);if(!t||!t.alive)return false;ensure(a);ensure(t);const w=profile(a),d=Math.hypot(t.x-a.x,t.y-a.y),isGun=w.family==='firearm';if(style==='stomp'&&sim.minute>=ensure(t).knockedUntil)return false;if(d>(isGun?w.range:w.reach+8)){a.target={x:t.x,y:t.y,id:t.id};a.action={tool:'attack',args:{target_id:id,style,_phase:'approach',reason:meta.reason||''},started:sim.minute,duration:Math.min(12,d/44),progress:0,model:'local-intent'};return true}const fatigue=1+(100-a.energy)/180+a.pain/250+(a.bodyClock?.sleepPressure||0)/300,aStyle=STYLE[style]||STYLE.balanced;baseGuard(a,style);a.action={tool:'attack_v08',args:{target_id:id,style,reason:meta.reason||''},started:sim.minute,duration:Math.max(.45,(isGun?.75:1.15)*aStyle.time*fatigue),progress:0,model:'local-intent'};return true}
function baseGuard(a,style){const c=ensure(a),s=STYLE[style]||STYLE.balanced;c.guard=clamp(c.guard+s.guard,0,1);if(style==='defensive')c.stance='defensive'}
function finish(a,id,style='balanced'){const t=sim.entityById(id);if(!t||!t.alive)return false;const ac=ensure(a),tc=ensure(t),w=profile(a),sp=STYLE[style]||STYLE.balanced,d=Math.hypot(t.x-a.x,t.y-a.y),isGun=w.family==='firearm';if(sim.minute<ac.knockedUntil||d>(isGun?w.range:w.reach+10))return false;if(isGun&&sim.canSee&&!sim.canSee(a,t,w.range)){sim.remember(a,'combat','Não conseguiu uma linha de tiro limpa.',4,['combat']);return false}if(isGun){if(!w.ammo||!sim.itemQty(a,w.ammo)){sim.remember(a,'combat',`${w.name} está sem munição.`,5,['combat']);return false}sim.takeItem(a,w.ammo,1);sim.emitNoise(a.x,a.y,w.noise,'gunshot',a.id,'disparo de arma de fogo')}else sim.emitNoise(a.x,a.y,w.noise,'melee',a.id,'impacto de combate');
 const skill=sim.skillLevel(a,w.skill),fatigue=(100-a.energy)/100,pain=a.pain/100,stress=a.stress/100,sleep=(a.bodyClock?.sleepPressure||0)/100,distPenalty=isGun?clamp(d/w.range,0,1)*.34:clamp(Math.max(0,d-w.reach*.55)/Math.max(1,w.reach*.55),0,1)*.12,recoil=isGun?ac.recoil*.24:0,targetDefense=t.kind==='person'?(t.attr?.agility||4)*.018+sim.skillLevel(t,'melee')*.025+tc.guard*.18-woundPenalty(t):0,crowdBonus=t.kind==='person'?crowd(t,a)*.025:0;let hit=clamp(.5+(w.accuracy||0)+skill*.045+(a.attr.agility||4)*.012+w.control*.12+sp.acc-targetDefense-distPenalty-recoil-fatigue*.18-pain*.18-stress*.1-sleep*.12+crowdBonus,.05,.98);if(style==='stomp')hit=clamp(hit+.2,.2,.99);a.energy=clamp(a.energy-(w.stamina||3)*sp.energy*(isGun?.45:1),0,100);a.stress=clamp(a.stress+(isGun?2.8:1.3),0,100);ac.lastAttack=sim.minute;sim.practice(a,w.skill,3);if(!isGun)sim.practice(a,'melee',1.3);if(!sim.rng.chance(hit)){sim.effects.push({type:'miss',x:t.x,y:t.y,life:10});ac.recoil=isGun?clamp(ac.recoil+.16,0,1):ac.recoil;return false}
 const z=zone(a,t,style,isGun),base=(w.damage||4)+(isGun?(a.attr.perception||4)*.25:(a.attr.strength||4)*1.05)+skill*1.55+sim.rng.range(-3,6),damage=Math.max(1,base*sp.dmg*(z==='cabeça'?1.42:z==='perna'?.88:z==='braço'?.8:1));let dealt=damage;if(t.kind==='person')dealt=humanTrauma(a,t,damage,w,z);else{t.health-=damage;tc.balance=clamp(tc.balance-damage*(z==='perna'?1.15:.45),0,100)}tc.lastHit=sim.minute;impulse(a,t,style,dealt,w);t.hitFlashUntil=performance.now()+210;sim.effects.push({type:'impact_v08',x:t.x,y:t.y,life:10,amount:Math.round(dealt)});if(tc.balance<14&&sim.rng.chance(.52)){tc.knockedUntil=sim.minute+sim.rng.range(1.2,3.8);tc.balance=8;if(t.kind==='person'){t.action=null;t.target=null}}if(isGun)ac.recoil=clamp(ac.recoil+.24,0,1);if(t.health<=0){if(t.kind==='zombie'){t.alive=false;credit(a,t,'combat')}else{credit(a,t,'combat');sim.killPerson(t,`ataque de ${a.name}`)}}return true}
function tickEntity(e,dt){const c=ensure(e);if(c.impulse){const k=c.impulse,decay=Math.exp(-8*Math.max(0,dt));e.x+=k.vx*dt;e.y+=k.vy*dt;k.vx*=decay;k.vy*=decay;if(Math.hypot(k.vx,k.vy)<2)c.impulse=null}c.guard=clamp(c.guard-dt*.01,0,1);c.recoil=clamp(c.recoil-dt*.08,0,1);if(sim.minute>=c.knockedUntil&&c.balance<100)c.balance=clamp(c.balance+dt*.16,0,100)}
function zombieAfterWound(z,p){ensure(p);const c=ensure(p),n=crowd(p,z),chance=clamp(.12+n*.07+(100-p.energy)*.0025+(p.stress||0)*.0015-(p.attr.strength||4)*.015-sim.skillLevel(p,'melee')*.02,.04,.68);if(sim.rng.chance(chance)){c.grabbedBy=z.id;c.grabbedUntil=sim.minute+sim.rng.range(.8,2.6);c.balance=clamp(c.balance-18-n*4,0,100)}V.ensurePerson(p);V.learnFact(p,'anomaly:violent-human','Pessoas gravemente feridas podem continuar atacando de forma anormal.', 'sensor', .88,{firsthand:true})}
function escapeGrab(p){const c=ensure(p);if(!c.grabbedBy||sim.minute>=c.grabbedUntil){c.grabbedBy=null;return true}const z=sim.entityById(c.grabbedBy),pressure=crowd(p,z),chance=clamp(.34+p.attr.strength*.035+p.attr.agility*.025+sim.skillLevel(p,'melee')*.035-p.stress*.0025-pressure*.07,.08,.9);p.energy=clamp(p.energy-5,0,100);if(sim.rng.chance(chance)){c.grabbedBy=null;c.grabbedUntil=0;c.balance=clamp(c.balance+14,0,100);if(z){const dx=z.x-p.x,dy=z.y-p.y,l=Math.hypot(dx,dy)||1;z.combat=ensure(z);z.combat.impulse={vx:dx/l*105,vy:dy/l*105}}sim.remember(p,'combat','Conseguiu se soltar de um agarrão.',6,['combat']);return true}return false}
V.combat={ensure,profile,start,finish,tickEntity,zombieAfterWound,escapeGrab,credit};sim.creditKill=credit;sim.combatSummary=(p,forBrain=false)=>{const c=ensure(p),w=profile(p),out={weapon:w.name||w.id,weapon_family:w.family,stance:c.stance,balance:c.balance>78?'firme':c.balance>48?'estável':c.balance>22?'instável':'quase caindo',guard:c.guard>.55?'alta':c.guard>.22?'moderada':'baixa',knocked:sim.minute<c.knockedUntil,grabbed:!!(c.grabbedBy&&sim.minute<c.grabbedUntil)};if(!forBrain)out.nearby_attackers=crowd(p);return out};
const attack=AZ.AGENT_TOOLS?.find(t=>t.function?.name==='attack');if(attack){attack.function.description='Atacar alvo percebido; alcance, arma, fadiga, equilíbrio, dor, habilidade e defesa afetam o resultado.';attack.function.parameters.properties.style={type:'string',enum:['quick','balanced','heavy','push','aimed','defensive','stomp']}}if(!AZ.AGENT_TOOLS?.some(t=>t.function?.name==='combat_stance'))AZ.AGENT_TOOLS.push({type:'function',function:{name:'combat_stance',description:'Mudar postura de combate.',parameters:{type:'object',properties:{stance:{type:'string',enum:['aggressive','balanced','defensive','distance']},reason:{type:'string'}},required:['stance','reason'],additionalProperties:false}}});
for(const p of sim.people){V.ensurePerson(p);ensure(p)}for(const z of sim.zombies)ensure(z);
})();
