'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ,W=AZ?.WorldV9,world=sim?.world;if(!sim||!AZ||!W||!world?.requestChunk)return;const CS=AZ.CHUNK_SIZE,perf=sim.performanceCore||{};perf.version='0.11';
const M=sim.zombieMigration={version:'0.11',cells:new Map(),activeCap:120,realized:0,abstracted:0,moved:0,ticks:0,lastMinute:sim.minute,lastReal:performance.now()};
const k=(cx,cy)=>`${cx},${cy}`,parse=s=>s.split(',').map(Number),chunkOf=(x,y)=>({cx:AZ.chunkCoord(x),cy:AZ.chunkCoord(y)});
function baseline(cx,cy){const x=(cx+.5)*CS,y=(cy+.5)*CS,zone=W.zoneAt(world,x,y),r=AZ.rand01(sim.seed,cx,cy,61101),base=zone==='center'?20:zone==='urban'?14:zone==='suburb'?8:zone==='rural'?3:1,span=zone==='center'?12:zone==='urban'?10:zone==='suburb'?8:zone==='rural'?5:3;return Math.max(0,base+Math.floor(r*(span+1)))}
function cell(cx,cy){const id=k(cx,cy);let c=M.cells.get(id);if(!c){c={cx,cy,latent:baseline(cx,cy),base:baseline(cx,cy),spawnSeq:0,lastTouched:sim.minute};M.cells.set(id,c)}c.lastTouched=sim.minute;return c}
function absorbExisting(){for(const z of sim.zombies){if(!z.alive||z._migrationManaged)continue;const q=chunkOf(z.x,z.y),c=cell(q.cx,q.cy);c.latent=Math.max(0,c.latent-1);z._migrationManaged=true}}
absorbExisting();
const makeZombieBase=sim.makeZombie.bind(sim);sim.makeZombie=function(...args){const z=makeZombieBase(...args);z._migrationManaged=true;z._migrationFresh=true;return z};
function people(){return sim.people.filter(p=>p.alive)}
function nearAnyHuman(x,y,r){const r2=r*r;for(const p of sim.peopleGrid.near(x,y,r))if(p.alive&&(p.x-x)**2+(p.y-y)**2<=r2)return true;return false}
function ensureInterest(){const allowed=new Set();for(const p of people()){const q=chunkOf(p.x,p.y);for(let oy=-4;oy<=4;oy++)for(let ox=-4;ox<=4;ox++)if(Math.abs(ox)+Math.abs(oy)<=4){const id=k(q.cx+ox,q.cy+oy);allowed.add(id);cell(q.cx+ox,q.cy+oy)}}return allowed}
function edgeRoad(cx,cy,nx,ny){const e=world.chunkEdges(cx,cy),dx=nx-cx,dy=ny-cy;if(dx===1)return e.E;if(dx===-1)return e.W;if(dy===1)return e.S;if(dy===-1)return e.N;return false}
function migrate(elapsed){const allowed=ensureInterest(),humans=new Map(),noise=new Map();for(const p of people()){const q=chunkOf(p.x,p.y),id=k(q.cx,q.cy);humans.set(id,(humans.get(id)||0)+1)}for(const n of sim.noiseEvents||[]){if(n.expires<=sim.minute)continue;const q=chunkOf(n.x,n.y),id=k(q.cx,q.cy);noise.set(id,(noise.get(id)||0)+n.loudness)}const delta=new Map(),factor=Math.min(2.5,Math.max(.15,elapsed/30)),dirs=[[1,0],[-1,0],[0,1],[0,-1]],bucket=Math.floor(sim.minute/20);for(const c of [...M.cells.values()]){const sid=k(c.cx,c.cy);if(!allowed.has(sid)||c.latent<=0)continue;const sourceScore=(humans.get(sid)||0)*7+(noise.get(sid)||0)*8+(c.latent>c.base?2:0);let best=null,bestScore=sourceScore;for(const[dX,dY]of dirs){const nid=k(c.cx+dX,c.cy+dY);if(!allowed.has(nid))continue;const nc=cell(c.cx+dX,c.cy+dY),road=edgeRoad(c.cx,c.cy,nc.cx,nc.cy),gap=Math.max(-4,Math.min(6,nc.base-(nc.latent+(delta.get(nid)||0)))),score=(humans.get(nid)||0)*7+(noise.get(nid)||0)*8+(road?2.2:0)+gap*.35+AZ.rand01(sim.seed,nc.cx,nc.cy,61200+bucket)*.35;if(score>bestScore+.55){bestScore=score;best=nc}}if(!best&&c.latent>c.base*1.35){const opts=dirs.map(([dx,dy])=>k(c.cx+dx,c.cy+dy)).filter(id=>allowed.has(id)).map(id=>{const [x,y]=parse(id);return cell(x,y)});best=opts.sort((a,b)=>(a.latent-a.base)-(b.latent-b.base))[0]||null}if(!best)continue;const stochastic=AZ.rand01(sim.seed,c.cx,c.cy,61300+bucket),move=Math.min(3,c.latent,Math.floor(c.latent*.075*factor+stochastic*.9));if(move<=0)continue;delta.set(sid,(delta.get(sid)||0)-move);const bid=k(best.cx,best.cy);delta.set(bid,(delta.get(bid)||0)+move);M.moved+=move}for(const[id,d]of delta){const [cx,cy]=parse(id),c=cell(cx,cy);c.latent=Math.max(0,c.latent+d)}for(const[id,c]of M.cells)if(!allowed.has(id)&&c.latent===c.base&&sim.minute-c.lastTouched>180)M.cells.delete(id);M.ticks++}
function spawnIn(c){const loaded=world.peekChunk(c.cx,c.cy);if(!loaded){world.requestChunk(c.cx,c.cy,9,'zombie-realization');return null}for(let attempt=0;attempt<8;attempt++){const n=c.spawnSeq++,rx=.08+AZ.rand01(sim.seed,c.cx,c.cy,62000+n*3)*.84,ry=.08+AZ.rand01(sim.seed,c.cy,c.cx,62001+n*3)*.84,x=(c.cx+rx)*CS,y=(c.cy+ry)*CS,q=world.nearestWalkable(x,y,null,5);if(!nearAnyHuman(q.x,q.y,85))return q}return null}
function realize(){let active=sim.zombies.reduce((n,z)=>n+(z.alive?1:0),0),spawnBudget=12;if(active>=M.activeCap)return;const targets=new Map();for(const p of people()){const q=chunkOf(p.x,p.y);for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const id=k(q.cx+ox,q.cy+oy);targets.set(id,cell(q.cx+ox,q.cy+oy))}}const activeBy=new Map();for(const z of sim.zombies)if(z.alive){const q=chunkOf(z.x,z.y),id=k(q.cx,q.cy);activeBy.set(id,(activeBy.get(id)||0)+1)}for(const[id,c]of targets){if(active>=M.activeCap||spawnBudget<=0)break;let local=activeBy.get(id)||0,quota=Math.min(2,8-local,c.latent,spawnBudget);while(quota-->0&&c.latent>0&&active<M.activeCap&&spawnBudget>0){const p=spawnIn(c);if(!p)break;const z=sim.makeZombie(p.x,p.y,null);z._migrationManaged=true;sim.zombies.push(z);c.latent--;local++;active++;spawnBudget--;M.realized++}activeBy.set(id,local)}}
function abstractFar(){const ppl=people();if(!ppl.length)return;const keep=[],far=CS*2.8,idx=perf.entityIndex;for(const z of sim.zombies){if(!z.alive){if(sim.selected===z)keep.push(z);else{sim.zombieGrid?._remove?.(z);idx?.delete?.(z.id)}continue}let close=false;for(const p of ppl){if(Math.abs(p.x-z.x)>far||Math.abs(p.y-z.y)>far)continue;if(Math.hypot(p.x-z.x,p.y-z.y)<=far){close=true;break}}if(close||sim.selected===z){keep.push(z);continue}const q=chunkOf(z.x,z.y),c=cell(q.cx,q.cy);c.latent++;sim.zombieGrid?._remove?.(z);idx?.delete?.(z.id);z.alive=false;z._abstracted=true;M.abstracted++}if(keep.length!==sim.zombies.length)sim.zombies=keep}
let lastInterest=0,nextGeneration=0,lastMigrationReal=performance.now();function prefetch(){const now=performance.now();if(now-lastInterest<180)return;lastInterest=now;for(const p of people()){const cx=AZ.chunkCoord(p.x),cy=AZ.chunkCoord(p.y),lx=((p.x%CS)+CS)%CS,ly=((p.y%CS)+CS)%CS;world.requestChunk(cx,cy,10,'resident');if(lx<180)world.requestChunk(cx-1,cy,7,'edge-prefetch');if(lx>CS-180)world.requestChunk(cx+1,cy,7,'edge-prefetch');if(ly<180)world.requestChunk(cx,cy-1,7,'edge-prefetch');if(ly>CS-180)world.requestChunk(cx,cy+1,7,'edge-prefetch');if(p.target){const tx=AZ.chunkCoord(p.target.x),ty=AZ.chunkCoord(p.target.y);world.requestChunk(tx,ty,8,'intent-target')}}}
const baseUpdate=sim.update.bind(sim);sim.update=function(dt){const frameStart=performance.now();prefetch();baseUpdate(dt);absorbExisting();const now=performance.now(),elapsed=Math.max(0,Math.min(120,sim.minute-M.lastMinute));if(!sim.paused&&now-lastMigrationReal>1100){lastMigrationReal=now;M.lastMinute=sim.minute;migrate(elapsed);abstractFar();realize()}const spent=performance.now()-frameStart;if(now>=nextGeneration&&world.generationQueue?.size){const made=world.processGenerationQueue(spent<8?1:0,3.5);if(made){const ms=world.generationStats.lastMs||0;nextGeneration=now+(ms>12?180:ms>7?100:ms>4?55:25)}}};
M.snapshot=()=>({cells:M.cells.size,latent:[...M.cells.values()].reduce((n,c)=>n+c.latent,0),active:sim.zombies.reduce((n,z)=>n+(z.alive?1:0),0),realized:M.realized,abstracted:M.abstracted,moved:M.moved,ticks:M.ticks});
})();
