'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ;if(!sim||!AZ)return;
const V=window.AZV8=window.AZV8||{};V.version='0.8.0';
const clamp=AZ.clamp;V.clamp=clamp;
V.isAgent=p=>p?.kind==='person'&&p.type==='agent';
V.qual={
 need:v=>v>85?'crítico':v>68?'alto':v>45?'moderado':v>22?'baixo':'muito baixo',
 health:v=>v>82?'boa':v>62?'razoável':v>38?'comprometida':v>18?'grave':'crítica',
 stat:v=>v>=8?'excelente':v>=6?'forte':v>=4?'mediano':'fraco',
 relation:v=>v>65?'muito positiva':v>25?'positiva':v<-65?'hostil':v<-25?'negativa':'neutra',
 confidence:v=>v>.84?'muito alta':v>.64?'alta':v>.42?'moderada':v>.2?'baixa':'muito baixa',
 distance:d=>d<45?'muito perto':d<110?'perto':d<220?'distância média':d<420?'longe':'muito longe'
};
V.dirName=(dx,dy)=>['E','SE','S','SW','W','NW','N','NE','E'][(Math.round(Math.atan2(dy,dx)/(Math.PI/4))+8)%8];
V.pointRectDist=(x,y,s)=>{const dx=Math.max(s.x-x,0,x-(s.x+(s.w||0))),dy=Math.max(s.y-y,0,y-(s.y+(s.h||0)));return Math.hypot(dx,dy)};
V.topicKey=text=>{const s=String(text||'').toLowerCase();if(/usina|explos|fumaça|reator/.test(s))return'event:plant';if(/exército|militar|soldad|checkpoint|bloqueio/.test(s))return'institution:army';if(/água|agua|poço|contamin/.test(s))return'resource:water';if(/comida|alimento|mercado|fome/.test(s))return'resource:food';if(/segur|abrigo|refúgio|refugio/.test(s))return'place:safety';if(/mord|arranh|corte|agress|cambale|reanim|zumbi|infectad/.test(s))return'anomaly:violent-human';let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return`rumor:${(h>>>0).toString(36)}`};
V.ensurePerson=p=>{if(!p)return p;p.stats=p.stats||{kills:0,zombieKills:0,humanKills:0,vehicleKills:0};for(const k of ['kills','zombieKills','humanKills','vehicleKills'])p.stats[k]=p.stats[k]||0;if(!Number.isFinite(p.facing))p.facing=0;p.bodyClock=p.bodyClock||{sleepPressure:20+((p.id?.length||1)*7)%24,sleeping:false,lastSleepDay:0,scars:[],illness:0,fever:0,mobility:1};p.brain=p.brain||{};Object.assign(p.brain,{intent:p.brain.intent||null,nextIntent:p.brain.nextIntent||null,replanPending:p.brain.replanPending||null,requestEvent:p.brain.requestEvent||null,plan:p.brain.plan||null,identitySummary:p.brain.identitySummary||'',lastIdentityDay:p.brain.lastIdentityDay||0,lastPlanPeriod:Number.isFinite(p.brain.lastPlanPeriod)?p.brain.lastPlanPeriod:-1,initialPlanRequested:!!p.brain.initialPlanRequested});p.beliefs=p.beliefs instanceof Map?p.beliefs:new Map();p.mentalMap=p.mentalMap instanceof Map?p.mentalMap:new Map();p.socialModel=p.socialModel instanceof Map?p.socialModel:new Map();p.lexicon=p.lexicon||{};p._v8=p._v8||{sensorAt:0,threatIds:new Set(),bodySig:'',wounds:(p.wounds||[]).length,novelty:p.brain.novelty||0,intentSeq:0,lastActionTool:null,lastActionEnd:performance.now(),lastPos:{x:p.x,y:p.y},lastMotionAt:performance.now()};return p};
V.ensureZombie=z=>{if(!z)return z;z.combat=z.combat||{balance:100,guard:0,knockedUntil:0,grabbedBy:null,recoil:0};return z};
V.social=(a,b)=>{V.ensurePerson(a);let s=a.socialModel.get(b.id);if(!s){const legacy=a.relations?.get(b.id)||0;s={affinity:clamp(legacy,-100,100),trust:clamp(legacy*.72+10,-100,100),debt:0,fear:Math.max(0,-legacy*.25),familiarity:clamp(Math.abs(legacy)*.35,0,100),lastInteraction:sim.minute,estimatedGoal:null,knownBeliefs:new Set()};a.socialModel.set(b.id,s)}return s};
V.learnFact=(p,key,content,source='self',confidence=.65,meta={})=>{V.ensurePerson(p);const now=sim.minute,k=key||V.topicKey(content),old=p.beliefs.get(k),firsthand=source==='self'||source==='sensor';if(!old){p.beliefs.set(k,{key:k,content:String(content),source,learnedAt:now,lastUpdated:now,confidence:clamp(confidence,0,1),firsthand,contradictions:0,...meta})}else if(old.content===String(content)){old.confidence=clamp(old.confidence+(firsthand?.18:.07)*(1-old.confidence),0,1);old.lastUpdated=now;if(firsthand)old.firsthand=true}else{const incoming=clamp(confidence,0,1),resistance=(old.firsthand?.22:0)+(old.confidence*.45);if(incoming>resistance){old.contradictions=(old.contradictions||0)+1;old.previous=old.content;old.content=String(content);old.source=source;old.confidence=clamp((old.confidence*.45+incoming*.75)/1.2,0,1);old.firsthand=firsthand;old.lastUpdated=now}else{old.contradictions=(old.contradictions||0)+1;old.confidence=clamp(old.confidence-.04,0,1)}}if(p.beliefs.size>64){const arr=[...p.beliefs.values()].sort((a,b)=>(a.confidence+(a.firsthand?.4:0))-(b.confidence+(b.firsthand?.4:0)));for(const x of arr.slice(0,p.beliefs.size-64))p.beliefs.delete(x.key)}return p.beliefs.get(k)};
V.learnPlace=(p,s)=>{if(!p||!s)return;V.ensurePerson(p);p.mentalMap.set(s.id,{id:s.id,name:s.name||s.type,type:s.type,lastSeen:sim.minute,condition:s.fire>0?'em chamas':s.barricade>0?'barricado':'aparentemente acessível',x:Math.round(s.x+(s.w||0)/2),y:Math.round(s.y+(s.h||0)/2)});if(p.mentalMap.size>90){const old=[...p.mentalMap.values()].sort((a,b)=>a.lastSeen-b.lastSeen);for(const x of old.slice(0,p.mentalMap.size-90))p.mentalMap.delete(x.id)}};
V.rebuildMemoryIndex=p=>{if(!p.memory)return;p.memory.byTag=new Map();for(const m of p.memory.entries||[])for(const t of m.tags||[]){if(!p.memory.byTag.has(t))p.memory.byTag.set(t,[]);p.memory.byTag.get(t).push(m)}};
V.consolidateMemory=(p,day)=>{if(!p.memory?.entries?.length)return;const start=(day-1)*1440,end=day*1440,dayItems=p.memory.entries.filter(m=>m.minute>=start&&m.minute<end&&m.kind!=='daily_summary'),top=dayItems.slice().sort((a,b)=>b.importance-a.importance).slice(0,7);if(top.length){const text=`Resumo do dia ${day}: `+top.map(m=>m.text).join(' | ');const exists=p.memory.entries.some(m=>m.kind==='daily_summary'&&m.tags?.includes(`day:${day}`));if(!exists)p.memory.add(end-.01,'daily_summary',text,9,['summary',`day:${day}`])}const now=sim.minute;p.memory.entries=p.memory.entries.filter(m=>{if(m.kind==='daily_summary'||m.importance>=9)return true;const age=now-m.minute;if(age>4320&&m.importance<8)return false;if(m.minute>=start&&m.minute<end&&m.importance<7)return false;return true});if(p.memory.entries.length>220){const keep=p.memory.entries.slice().sort((a,b)=>(b.importance+(b.kind==='daily_summary'?5:0))-(a.importance+(a.kind==='daily_summary'?5:0))).slice(0,220);keep.sort((a,b)=>a.minute-b.minute);p.memory.entries=keep}V.rebuildMemoryIndex(p)};
sim.currentSite=p=>{const direct=sim.world.siteAt(p.x,p.y);if(direct)return direct;return sim.world.nearbySites(p.x,p.y,72).sort((a,b)=>V.pointRectDist(p.x,p.y,a)-V.pointRectDist(p.x,p.y,b)).find(s=>V.pointRectDist(p.x,p.y,s)<=28)||null};
sim.distanceToEntity=(p,t)=>!t?Infinity:t.kind==='site'?V.pointRectDist(p.x,p.y,t):Math.hypot((t.x+(t.w||0)/2)-p.x,(t.y+(t.h||0)/2)-p.y);
sim.noiseEvents=sim.noiseEvents||[];sim.emitNoise=(x,y,loudness=.2,kind='noise',sourceId=null,label='ruído')=>{const e={id:`n${Date.now()}${Math.random()}`,x,y,loudness:clamp(loudness,0,1.5),kind,sourceId,label,minute:sim.minute,expires:sim.minute+Math.max(1,4+loudness*18)};sim.noiseEvents.push(e);if(sim.noiseEvents.length>160)sim.noiseEvents.splice(0,sim.noiseEvents.length-160);return e};
const segRect=(x1,y1,x2,y2,r)=>{for(let i=1;i<5;i++){const t=i/5,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(x>r.x&&x<r.x+r.w&&y>r.y&&y<r.y+r.h)return true}return false};
sim.canSee=(a,t,maxRange)=>{const tx=t.x+(t.w||0)/2,ty=t.y+(t.h||0)/2,dx=tx-a.x,dy=ty-a.y,d=Math.hypot(dx,dy);if(d>maxRange)return false;if(d>42){const da=Math.abs(Math.atan2(Math.sin(Math.atan2(dy,dx)-(a.facing||0)),Math.cos(Math.atan2(dy,dx)-(a.facing||0))));if(da>1.42)return false}for(const s of sim.world.nearbySites((a.x+tx)/2,(a.y+ty)/2,Math.min(350,d*.65))){if(t.id===s.id)continue;if(segRect(a.x,a.y,tx,ty,s))return false}return true};
sim.craftingRecipes={spear:{name:'Lança improvisada',need:{wood:2,metal:1},out:{id:'spear',name:'Lança improvisada',kind:'weapon',qty:1,weight:2.1},minutes:18,skill:'carpentry'},bandage:{name:'Curativo improvisado',need:{cloth:1},out:{id:'bandage',name:'Curativo',kind:'medical',qty:1,weight:.2},minutes:5,skill:'first_aid'},water_filter:{name:'Filtro de água',need:{cloth:1,metal:1},out:{id:'water_filter',name:'Filtro de água',kind:'utility',qty:1,weight:.8},minutes:14,skill:'foraging'},torch:{name:'Tocha',need:{wood:1,cloth:1},out:{id:'torch',name:'Tocha',kind:'utility',qty:1,weight:.7},minutes:8,skill:'foraging'},backpack:{name:'Mochila improvisada',need:{cloth:3},out:{id:'backpack',name:'Mochila',kind:'utility',qty:1,weight:.8},minutes:24,skill:'carpentry'},wooden_club:{name:'Porrete de madeira',need:{wood:2},out:{id:'wooden_club',name:'Porrete de madeira',kind:'weapon',qty:1,weight:1.5},minutes:10,skill:'carpentry'},improvised_knife:{name:'Faca improvisada',need:{metal:1,cloth:1},out:{id:'improvised_knife',name:'Faca improvisada',kind:'weapon',qty:1,weight:.55},minutes:16,skill:'carpentry'}};
sim.knownCraftingRecipes=p=>Object.entries(sim.craftingRecipes).map(([id,r])=>({id,name:r.name,minutes:r.minutes,can_make:sim.hasNeed(p,r.need),needs:Object.entries(r.need).map(([item,need])=>({item,need,have:sim.itemQty(p,item)}))}));
const craftTool=AZ.AGENT_TOOLS?.find(t=>t.function?.name==='craft');if(craftTool){craftTool.function.description='Fabricar um item conhecido usando materiais carregados. Use um id listado em crafting.recipes.';craftTool.function.parameters.properties.recipe={type:'string',description:'id exato de uma receita conhecida'};}
for(const p of sim.people)V.ensurePerson(p);for(const z of sim.zombies)V.ensureZombie(z);for(const s of sim.structures||[])if(!s.kind)s.kind='structure';
})();
