'use strict';
(()=>{
const sim=window.sim,ai=sim?.ai,S=sim?.social,V=window.AZV8,$=id=>document.getElementById(id);if(!sim||!ai||!S||!V)return;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const version=document.querySelector('.drawerHead small');if(version)version.textContent='v0.10.0 · sociedade emergente + IA econômica';if($('lightModel'))$('lightModel').value=ai.lightModel;if($('deepModel'))$('deepModel').value=ai.deepModel;
const tabs=document.querySelector('.tabs');if(tabs&&!document.querySelector('[data-tab="social"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='social';b.textContent='Social';tabs.appendChild(b);b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('socialPanel')?.classList.add('active');renderSocial()}}
if(!$('socialPanel')){const sec=document.createElement('section');sec.className='panel';sec.id='socialPanel';sec.innerHTML='<h3>Sociedade emergente</h3><div id="socialGroups"></div><h3>Cenas recentes</h3><div id="socialScenes"></div>';$('drawer')?.appendChild(sec)}
const style=document.createElement('style');style.textContent='.v10box{border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:8px;margin:6px 0;background:rgba(255,255,255,.025)}.v10box small{display:block;opacity:.68;margin-top:3px}.v10turn{padding:4px 0;border-top:1px solid rgba(255,255,255,.05)}.v10member{border:0;background:transparent;color:inherit;text-decoration:underline;padding:0;margin-right:5px}.v10metric{display:grid;grid-template-columns:1fr auto;gap:6px;margin:4px 0}.v10guard{opacity:.88}.v10guard input[type=number]{width:100%}';document.head.appendChild(style);
function name(id){return sim.entityById(id)?.name||id}
function focus(id){const p=sim.entityById(id);if(!p)return;sim.selected=p;window.renderer?.centerOnSelected?.();window.dispatchEvent(new CustomEvent('az-selection',{detail:p}));document.querySelector('[data-tab="inspect"]')?.click()}
function renderSocial(){const g=$('socialGroups'),s=$('socialScenes');if(g){g.innerHTML=S.groups.length?S.groups.map(x=>`<div class="v10box"><b>${x.members.length} pessoas</b><small>liderança percebida: ${esc(name(x.leader))}</small><div>${x.members.map(id=>`<button class="v10member" data-person="${esc(id)}">${esc(name(id))}</button>`).join('')}</div><small>normas emergentes: ${esc(x.norms.join(' · ')||'nenhuma estável ainda')}</small></div>`).join(''):'<div class="v10box"><small>Nenhum grupo social estável emergiu ainda.</small></div>';g.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>focus(b.dataset.person))}if(s){const rows=S.scenes.slice(-12).reverse();s.innerHTML=rows.length?rows.map(sc=>`<div class="v10box"><b>${esc(sc.outcome?.summary||sc.outcome?.type||'cena')}</b><small>${sim.formatMinute(sc.minute)} · ${sc.participants.map(name).map(esc).join(', ')}</small>${(sc.turns||[]).slice(0,5).map(t=>`<div class="v10turn"><b>${esc(name(t.speaker_id))}</b> ${esc(t.text)}</div>`).join('')}</div>`).join(''):'<div class="v10box"><small>Nenhuma cena social resolvida ainda.</small></div>'}}
const aiPanel=$('aiPanel');if(aiPanel&&!$('v10Economy')){const box=document.createElement('div');box.id='v10Economy';box.innerHTML=`<h3>Economia cognitiva</h3><label>Modelo social<input id="socialModel" class="field" value="${esc(ai.socialModel||ai.lightModel)}" /></label><div class="v10box"><div class="v10metric"><span>Chamadas no dia</span><b id="v10CallsDay">0</b></div><div class="v10metric"><span>Projeção/dia</span><b id="v10ProjectCalls">0</b></div><div class="v10metric"><span>Custo no dia</span><b id="v10CostDay">$0</b></div><div class="v10metric"><span>Queima estimada/h</span><b id="v10Burn">$0</b></div><div class="v10metric"><span>Cenas sociais</span><b id="v10Scenes">0</b></div></div><div class="v10box v10guard"><label class="switch"><input id="v10Guard" type="checkbox" /><span>Proteção opcional de gasto</span></label><label>Máx. chamadas/dia simulado · 0 = ilimitado<input id="v10GuardCalls" class="field" type="number" min="0" step="10" /></label><label>Máx. custo/dia em US$ · 0 = ilimitado<input id="v10GuardCost" class="field" type="number" min="0" step="0.01" /></label><small>Desativada por padrão. Sem proteção ativa, o simulador usa livremente o saldo disponível da OpenRouter.</small></div>`;aiPanel.appendChild(box);$('socialModel').onchange=e=>{ai.socialModel=String(e.target.value||'').trim()||ai.lightModel;localStorage.setItem('az_social_model',ai.socialModel)};$('v10Guard').checked=!!ai.economy.guard.enabled;$('v10GuardCalls').value=ai.economy.guard.maxCallsPerDay||0;$('v10GuardCost').value=ai.economy.guard.maxCostPerDay||0;const save=()=>ai.economy.saveGuard($('v10Guard').checked,$('v10GuardCalls').value,$('v10GuardCost').value);$('v10Guard').onchange=save;$('v10GuardCalls').onchange=save;$('v10GuardCost').onchange=save}
let socialTelemetry=$('v10SocialTelemetry');if(!socialTelemetry){socialTelemetry=document.createElement('div');socialTelemetry.id='v10SocialTelemetry';socialTelemetry.className='v10box hidden';($('stableAgentTelemetry')||$('inspector'))?.insertAdjacentElement('afterend',socialTelemetry)}
function renderTelemetry(){if(!socialTelemetry)return;const p=sim.selected;if(!p||p.kind!=='person'){socialTelemetry.classList.add('hidden');return}socialTelemetry.classList.remove('hidden');const rel=[...p.socialModel.entries()].map(([id,x])=>({q:sim.entityById(id),x})).filter(z=>z.q).sort((a,b)=>b.x.familiarity-a.x.familiarity).slice(0,6),group=S.groups.find(g=>g.members.includes(p.id));socialTelemetry.innerHTML=`<b>SOCIAL v0.10</b><small>${group?`grupo emergente com ${group.members.length} pessoas · liderança percebida ${esc(name(group.leader))}`:'sem grupo estável'}</small>${rel.map(({q,x})=>`<div class="v10turn"><b>${esc(q.name)}</b><small>afinidade ${Math.round(x.affinity||0)} · confiança ${Math.round(x.trust||0)} · dívida ${Math.round(x.debt||0)} · medo ${Math.round(x.fear||0)} · familiaridade ${Math.round(x.familiarity||0)} · respeito ${Math.round(x.respect||0)}</small></div>`).join('')}`}
setInterval(()=>{if(document.querySelector('[data-tab="social"]')?.classList.contains('active'))renderSocial();renderTelemetry();const m=ai.economy.metrics();if($('v10CallsDay'))$('v10CallsDay').textContent=m.callsDay;if($('v10ProjectCalls'))$('v10ProjectCalls').textContent=m.projectCallsPerSimDay;if($('v10CostDay'))$('v10CostDay').textContent='$'+m.costDay.toFixed(5);if($('v10Burn'))$('v10Burn').textContent='$'+m.costPerHour.toFixed(5);if($('v10Scenes'))$('v10Scenes').textContent=ai.socialCalls||0},850);
renderSocial();renderTelemetry();
})();
