'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ,W=AZ?.WorldV9;if(!sim||!AZ||!W||!sim.world)return;const world=sim.world,perf=sim.performanceCore=sim.performanceCore||{};
function scentGoal(z){const c=world.cellAtWorld(z.x,z.y);let best=null,score=0;for(let oy=-3;oy<=3;oy++)for(let ox=-3;ox<=3;ox++){const s=sim.scentMap?.get(`${c.gx+ox},${c.gy+oy}`);if(!s)continue;const age=sim.minute-s.minute,val=s.strength*Math.exp(-age/26)-Math.hypot(s.x-z.x,s.y-z.y)/700;if(val>score){score=val;best=s}}return best}
function nearestPerson(z,r=390){let best=null,bd=Infinity;for(const p of sim.peopleGrid.near(z.x,z.y,r)){if(!p.alive||p.vehicleId)continue;const d=(p.x-z.x)**2+(p.y-z.y)**2;if(d<bd){bd=d;best=p}}return best}
function senseZombie(z,st){perf.zombieSensePulses=(perf.zombieSensePulses||0)+1;z.mutation=world.radiationAt(z.x,z.y,sim.minute)*.24;let t=st.personId&&sim.entityById(st.personId);if(!t?.alive||t.vehicleId||Math.hypot(t.x-z.x,t.y-z.y)>520)t=null;if(!t)t=nearestPerson(z);if(t){st.personId=t.id;st.gx=t.x;st.gy=t.y;return true}st.personId=null;let best=null,bestScore=35;const idx=perf.noiseIndex,candidates=idx?.near?idx.near(z.x,z.y,900).map(n=>({n,d:Math.hypot(n.x-z.x,n.y-z.y)})).sort((a,b)=>(b.n.loudness*700-b.d)-(a.n.loudness*700-a.d)).slice(0,5):[];for(const q of candidates){const tr=world.lineTransmission(z.x,z.y,q.n.x,q.n.y),score=q.n.loudness*tr*700-q.d;if(score>bestScore){bestScore=score;best=q.n}}if(best){st.gx=best.x;st.gy=best.y;return false}const sc=scentGoal(z);if(sc){st.gx=sc.x;st.gy=sc.y;return false}if(!Number.isFinite(st.gx)||Math.hypot(st.gx-z.x,st.gy-z.y)<25){const q=world.randomPointNear(z.x,z.y,480,Math.floor(sim.minute)+z.id.length);st.gx=q.x;st.gy=q.y}return false}
sim.updateZombie=function(z,dt){if(!z.alive)return;const st=z._perfZombie||(z._perfZombie={nextSenseMinute:sim.minute+((z.id?.length||1)%7)*.08,personId:null,gx:z.x,gy:z.y});if(st.nextSenseMinute==null){st.nextSenseMinute=sim.minute;delete st.nextSense}
 if(Math.abs(z.knockVX||0)+Math.abs(z.knockVY||0)>.25){const km=world.tryMove(z.x,z.y,(z.knockVX||0)*dt,(z.knockVY||0)*dt,5,null);if(km.moved){z.x=km.x;z.y=km.y}const decay=Math.pow(.18,dt);z.knockVX=(z.knockVX||0)*decay;z.knockVY=(z.knockVY||0)*decay}
 if(z.combat&&sim.minute<(z.combat.knockedUntil||0))return;
 if(sim.minute>=st.nextSenseMinute){const tracking=senseZombie(z,st);st.nextSenseMinute=sim.minute+(tracking?.72:1.65)+((z.id?.charCodeAt?.(1)||0)%7)*.035}
 const t=st.personId&&sim.entityById(st.personId);if(t?.alive&&!t.vehicleId){st.gx=t.x;st.gy=t.y;const d=Math.hypot(t.x-z.x,t.y-z.y);if(d<25&&sim.minute>=z.nextAttack){z.nextAttack=sim.minute+sim.rng.range(.5,1.6);sim.zombieWound(z,t);if(t.health<=0)sim.killPerson(t,'ataque de infectado');return}}
 if(!Number.isFinite(st.gx)||!Number.isFinite(st.gy))return;const flow=world.flowDirection(z.x,z.y,st.gx,st.gy),l=Math.hypot(flow.x,flow.y)||1,speed=21+(z.mutation||0)*10,step=speed*dt,m=world.tryMove(z.x,z.y,flow.x/l*step,flow.y/l*step,5,null);if(m.moved){z.x=m.x;z.y=m.y;z.facing=Math.atan2(flow.y,flow.x)}else{const q=world.cellAtWorld(z.x+flow.x/l*10,z.y+flow.y/l*10),op=world.openingAtCell(q);if(op){const crowd=sim.zombieGrid.near(z.x,z.y,42).filter(x=>x.alive).length,damage=dt*(1.4+crowd*.22);world.damageOpening(op,damage);if(sim.minute-(z._barrierNoiseAt||-999)>.7){z._barrierNoiseAt=sim.minute;sim.emitNoise(op.x,op.y,.38,'barrier_hit',z.id,'impactos contra uma barreira')}}else if(sim.minute>=st.nextSenseMinute-.05){st.gx=NaN;st.gy=NaN}}
};
})();
