'use strict';
(()=>{
const sim=window.sim,AZ=window.AZ;if(!sim?.ai||!AZ)return;
const oldRemember=sim.remember.bind(sim),oldExecute=sim.executeAgentTool.bind(sim),oldAdvance=sim.advanceAction.bind(sim),oldFinish=sim.finishAction.bind(sim),oldWeaponStats=sim.weaponStats.bind(sim);
const ensure=p=>{p.brain.taskQueue=p.brain.taskQueue||[];p.brain.lastThought=p.brain.lastThought||'';p.stats=p.stats||{};p.stats.kills=p.stats.kills||0;p.stats.zombieKills=p.stats.zombieKills||0;p.stats.humanKills=p.stats.humanKills||0;p.stats.vehicleKills=p.stats.vehicleKills||0;if(!Number.isFinite(p.facing))p.facing=Math.random()*Math.PI*2};
for(const p of sim.people)ensure(p);
sim.remember=function(p,kind,text,importance,tags){ensure(p);if(kind==='thought'){p.brain.lastThought=String(text||'');return}const arr=p.memory?.entries||[],last=arr[arr.length-1];if(last&&last.kind===kind&&last.text===text&&this.minute-last.minute<8)return;return oldRemember(p,kind,text,importance,tags)};
sim.craftingRecipes={
 spear:{name:'Lança improvisada',need:{wood:2,metal:1},out:{id:'spear',name:'Lança improvisada',kind:'weapon',qty:1,weight:2.1},minutes:18,skill:'carpentry'},
 bandage:{name:'Curativo improvisado',need:{cloth:1},out:{id:'bandage',name:'Curativo',kind:'medical',qty:1,weight:.2},minutes:5,skill:'first_aid'},
 water_filter:{name:'Filtro de água',need:{cloth:1,metal:1},out:{id:'water_filter',name:'Filtro de água',kind:'utility',qty:1,weight:.8},minutes:14,skill:'foraging'},
 torch:{name:'Tocha',need:{wood:1,cloth:1},out:{id:'torch',name:'Tocha',kind:'utility',qty:1,weight:.7},minutes:8,skill:'foraging'},
 backpack:{name:'Mochila improvisada',need:{cloth:3},out:{id:'backpack',name:'Mochila',kind:'utility',qty:1,weight:.8},minutes:24,skill:'carpentry'},
 wooden_club:{name:'Porrete de madeira',need:{wood:2},out:{id:'wooden_club',name:'Porrete de madeira',kind:'weapon',qty:1,weight:1.5},minutes:10,skill:'carpentry'},
 improvised_knife:{name:'Faca improvisada',need:{metal:1,cloth:1},out:{id:'improvised_knife',name:'Faca improvisada',kind:'weapon',qty:1,weight:.55},minutes:16,skill:'carpentry'}
};
sim.weaponStats=function(p){const id=p.equippedWeapon&&this.itemQty(p,p.equippedWeapon)?p.equippedWeapon:null;if(id==='wooden_club')return{id,name:'Porrete de madeira',damage:15,range:31,accuracy:.12,stamina:5,skill:'blunt'};if(id==='improvised_knife')return{id,name:'Faca improvisada',damage:13,range:27,accuracy:.18,stamina:3.2,skill:'blade'};return oldWeaponStats(p)};
sim.knownCraftingRecipes=function(p){ensure(p);return Object.entries(this.craftingRecipes).map(([id,r])=>({id,name:r.name,minutes:r.minutes,can_make:this.hasNeed(p,r.need),needs:Object.entries(r.need).map(([k,v])=>({item:k,need:v,have:this.itemQty(p,k)}))}))};
const craftTool=AZ.AGENT_TOOLS?.find(t=>t.function?.name==='craft');if(craftTool){craftTool.function.description='Fabricar um item conhecido usando materiais carregados. Use um id listado em crafting.recipes.';craftTool.function.parameters.properties.recipe={type:'string',description:'id exato de uma receita em crafting.recipes'};}
sim.enqueueTask=function(p,name,args,meta={}){ensure(p);const q=p.brain.taskQueue;if(q.length>=4)return false;q.push({tool:name,args:{...args},model:meta.model||'brain',queuedAt:this.minute});return true};
sim.dispatchNextTask=function(p){ensure(p);if(p.action||!p.brain.taskQueue.length)return false;const t=p.brain.taskQueue.shift();this.executeAgentTool(p,t.tool,t.args,{model:t.model,fromQueue:true});return true};
sim.executeAgentTool=function(a,name,args={},meta={}){ensure(a);if(a.action&&!meta.fromQueue&&!meta.forceImmediate){this.enqueueTask(a,name,args,meta);return}
 if(name==='craft'){const r=this.craftingRecipes[args.recipe];if(!r){this.remember(a,'decision',`Não conhece a receita ${args.recipe||'solicitada'}.`,3,['decision','craft']);a.brain.nextDecision=this.minute+1;return}if(!this.hasNeed(a,r.need)){this.remember(a,'decision',`Queria fabricar ${r.name}, mas faltam materiais.`,3,['decision','craft']);a.brain.nextDecision=this.minute+1;return}const skill=this.skillLevel(a,r.skill||'carpentry'),dur=Math.max(2,r.minutes*(1.08-skill*.025));a.action={tool:'craft_v06',args:{...args,recipe:args.recipe,reason:args.reason||`fabricar ${r.name}`},started:this.minute,duration:dur,progress:0,model:meta.model||'brain'};a.brain.nextDecision=this.minute+Math.max(2,dur*.55);return}
 return oldExecute(a,name,args,meta)};
sim.finishAction=function(p,a){if(a.tool==='craft_v06'){const r=this.craftingRecipes[a.args.recipe];if(r&&this.consumeNeed(p,r.need)){this.addItem(p,r.out,1);this.practice(p,r.skill||'carpentry',5);this.remember(p,'craft',`Fabricou ${r.name}.`,6,['craft',r.out.id]);if(this.emitNoise)this.emitNoise(p.x,p.y,.22,'craft',p.id,'ruído de trabalho manual')}return}return oldFinish(p,a)};
sim.advanceAction=function(p,dt){ensure(p);const ox=p.x,oy=p.y,had=!!p.action;oldAdvance(p,dt);const dx=p.x-ox,dy=p.y-oy;if(Math.hypot(dx,dy)>.02)p.facing=Math.atan2(dy,dx);if(had&&!p.action)this.dispatchNextTask(p)};
sim.scheduleAgentBrain=function(p){ensure(p);if(!this.ai.enabled||!this.ai.apiKey){this.reflexFallback(p);return}if(p.brain.pending){if(p.brain.pendingSince&&performance.now()-p.brain.pendingSince>22000)this.ai.controllers.get(p.id)?.abort();return}if(performance.now()<(p.brain.retryAfter||0))return;if(p.brain.taskQueue.length&&!p.action){this.dispatchNextTask(p);return}if(this.minute<p.brain.nextDecision)return;const a=p.action,elapsed=a?this.minute-(a.started||this.minute):999,ratio=a?elapsed/Math.max(.5,a.duration||5):1;if(a&&p.brain.taskQueue.length>=2)return;if(a&&ratio<.42)return;const severe=p.health<45||p.infection>.35||p.radiation>.55||p.stress>82||p.brain.novelty>5||p.wounds.some(w=>w.infected),deep=severe&&this.minute>p.brain.complexCooldown;if(this.ai.decide(p,deep,a?'plan_ahead':'independent_cycle')){p.brain.nextDecision=this.minute+this.rng.range(4,9);if(deep)p.brain.complexCooldown=this.minute+180;p.brain.novelty=Math.max(0,p.brain.novelty-3)}};
})();
