'use strict';
(()=>{
const sim=window.sim;if(!sim?.ai)return;const ai=sim.ai,AZ=window.AZ;
sim.noiseEvents=sim.noiseEvents||[];
sim.emitNoise=function(x,y,loudness=.2,kind='noise',sourceId=null,label='ruído'){const e={id:`n${Date.now()}${Math.random()}`,x,y,loudness:AZ.clamp(loudness,0,1.5),kind,sourceId,label,minute:this.minute,expires:this.minute+Math.max(1,4+loudness*18)};this.noiseEvents.push(e);if(this.noiseEvents.length>160)this.noiseEvents.splice(0,this.noiseEvents.length-160);return e};
const dirName=(dx,dy)=>{const a=Math.atan2(dy,dx),i=Math.round(a/(Math.PI/4));return['E','SE','S','SW','W','NW','N','NE','E'][(i+8)%8]};
const band=d=>d<45?'muito perto':d<110?'perto':d<220?'distância média':d<420?'longe':'muito longe';
const rel=a=>a>60?'muito positiva':a>20?'positiva':a<-60?'hostil':a<-20?'negativa':'neutra';
function segRect(x1,y1,x2,y2,r){const steps=5;for(let i=1;i<steps;i++){const t=i/steps,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(x>r.x&&x<r.x+r.w&&y>r.y&&y<r.y+r.h)return true}return false}
sim.canSee=function(a,t,maxRange){const tx=t.x+(t.w||0)/2,ty=t.y+(t.h||0)/2,dx=tx-a.x,dy=ty-a.y,d=Math.hypot(dx,dy);if(d>maxRange)return false;if(d>42){const da=Math.abs(Math.atan2(Math.sin(Math.atan2(dy,dx)-a.facing),Math.cos(Math.atan2(dy,dx)-a.facing)));if(da>1.42)return false}const blockers=this.world.nearbySites((a.x+tx)/2,(a.y+ty)/2,Math.min(350,d*.65));for(const s of blockers){if(t.id===s.id)continue;if(segRect(a.x,a.y,tx,ty,s))return false}return true};
sim.socialContext=function(a){return this.peopleGrid.near(a.x,a.y,260).filter(p=>p.id!==a.id).slice(0,12).map(p=>({id:p.id,name:(a.relations.has(p.id)||Math.hypot(p.x-a.x,p.y-a.y)<70)?p.name:'pessoa desconhecida',relationship:rel(a.relations.get(p.id)||0),condition:this.publicCondition(p),uniform:p.military?'uniforme militar':null}))};
sim.sense=function(a){const range=170+a.attr.perception*28+this.skillLevel(a,'foraging')*4,seenPeople=[],seenFigures=[],seenSites=[],seenVehicles=[];
 for(const p of this.peopleGrid.near(a.x,a.y,range)){if(p.id===a.id||!this.canSee(a,p,range))continue;seenPeople.push({id:p.id,name:(a.relations.has(p.id)||Math.hypot(p.x-a.x,p.y-a.y)<70)?p.name:'pessoa desconhecida',distance:band(Math.hypot(p.x-a.x,p.y-a.y)),direction:dirName(p.x-a.x,p.y-a.y),condition:this.publicCondition(p),relationship:rel(a.relations.get(p.id)||0),uniform:p.military?'uniforme militar':null})}
 const visible=this.zombieGrid.near(a.x,a.y,range*1.08).filter(z=>this.canSee(a,z,range*1.08)).slice(0,10),knew=!!a.knowledge?.zombieSeen;if(visible.length)this.recordZombieSight(a,visible[0],knew?'repeat':'sight');for(const z of visible){seenFigures.push({id:z.id,distance:band(Math.hypot(z.x-a.x,z.y-a.y)),direction:dirName(z.x-a.x,z.y-a.y),appearance:knew?'figura humana agressiva com padrão já reconhecido':'pessoa com ferimentos graves, postura anormal e comportamento imprevisível',recognition:knew?'ameaça anormal reconhecida':'não compreendido'})}
 for(const s of this.world.nearbySites(a.x,a.y,range*1.25)){const c={x:s.x+s.w/2,y:s.y+s.h/2,id:s.id,w:0,h:0};if(!this.canSee(a,c,range*1.25))continue;seenSites.push({id:s.id,name:s.name,type:s.type,distance:band(Math.hypot(c.x-a.x,c.y-a.y)),direction:dirName(c.x-a.x,c.y-a.y),condition:s.fire>0?'em chamas':s.barricade>0?'barricado':'sem alteração óbvia'})}
 for(const v of this.world.nearbyVehicles(a.x,a.y,range*1.15)){if(!this.canSee(a,v,range*1.15))continue;seenVehicles.push({id:v.id,name:v.name,distance:band(Math.hypot(v.x-a.x,v.y-a.y)),direction:dirName(v.x-a.x,v.y-a.y),condition:v.condition>65?'aparenta funcionar':v.condition>30?'aparenta danificado':'muito danificado'})}
 const hearing=[];this.noiseEvents=this.noiseEvents.filter(n=>n.expires>this.minute);for(const n of this.noiseEvents){if(n.sourceId===a.id)continue;const d=Math.hypot(n.x-a.x,n.y-a.y),reach=90+n.loudness*(480+a.attr.perception*38);if(d>reach)continue;hearing.push({sound:n.label||n.kind,direction:dirName(n.x-a.x,n.y-a.y),distance:band(d),intensity:n.loudness>.85?'muito alto':n.loudness>.45?'alto':n.loudness>.2?'moderado':'baixo'})}
 const own=a.vehicleId?'alto':a.action?.tool==='attack'?'moderado':a.action?.tool==='craft_v06'?'moderado':a.action?'baixo':'quase silencioso';return{vision:{facing:dirName(Math.cos(a.facing),Math.sin(a.facing)),people:seenPeople.slice(0,12),unidentified_figures:seenFigures,sites:seenSites.slice(0,8),vehicles:seenVehicles.slice(0,6)},hearing:hearing.sort((x,y)=>({'muito alto':4,alto:3,moderado:2,baixo:1}[y.intensity]-({'muito alto':4,alto:3,moderado:2,baixo:1}[x.intensity]))).slice(0,10),own_noise:own,terrain:this.world.terrainAt(a.x,a.y),weather:'céu encoberto; vento perceptível'};
};
const q=v=>v>82?'crítico':v>62?'alto':v>38?'moderado':v>18?'baixo':'muito baixo',stat=v=>v>=8?'excelente':v>=6?'forte':v>=4?'mediano':'fraco';
ai.memoryContext=function(a){const raw=a.memory.retrieve({now:sim.minute,tags:sim.currentMemoryTags(a),limit:22}),out=[],seen=new Set();for(const m of raw.reverse()){if(m.kind==='thought')continue;const k=`${m.kind}|${m.text}`;if(seen.has(k))continue;seen.add(k);out.push({when:sim.formatMinute(m.minute),kind:m.kind,text:m.text});if(out.length>=14)break}return out.reverse()};
ai.buildContext=function(a,trigger){const wounds=(a.wounds||[]).map(w=>({type:w.type,severity:w.severity>.65?'grave':w.severity>.3?'moderada':'leve',bleeding:w.bleeding>.7?'forte':w.bleeding>.25?'moderado':'baixo'}));return{identity:{name:a.name,age:a.age,profession:a.profession,personality:a.personality,abilities:Object.fromEntries(Object.entries(a.attr).map(([k,v])=>[k,stat(v)])),goal:a.brain.goal||null},time:sim.timeLabel(),trigger,body:{health:q(100-a.health),hunger:q(a.hunger),thirst:q(a.thirst),fatigue:q(100-a.energy),stress:q(a.stress),pain:q(a.pain),bleeding:q(Math.min(100,a.bleeding*18)),wounds},inventory:a.inventory.map(i=>({id:i.id,name:i.name,kind:i.kind,qty:i.qty})),equipped:a.equippedWeapon||null,current_action:a.action?{tool:a.action.tool,reason:a.action.args?.reason||'',progress:a.action.duration?Math.min(1,(sim.minute-a.action.started)/a.action.duration):null}:null,task_queue:(a.brain.taskQueue||[]).map(t=>({tool:t.tool,reason:t.args?.reason||'',target:t.args?.target_id||t.args?.site_id||null})),sensors:sim.sense(a),social:sim.socialContext(a),crafting:{recipes:sim.knownCraftingRecipes(a)},memories:this.memoryContext(a)}};
})();
