'use strict';
(()=>{
const sim=window.sim,renderer=window.renderer;if(!sim||!renderer)return;
const oldAttack=sim.resolveAttack.bind(sim),oldTalk=sim.resolveTalk.bind(sim),oldDrive=sim.advanceDrive.bind(sim),oldUpdateZombie=sim.updateZombie.bind(sim);
const init=p=>{p.stats=p.stats||{};p.stats.kills=p.stats.kills||0;p.stats.zombieKills=p.stats.zombieKills||0;p.stats.humanKills=p.stats.humanKills||0;p.stats.vehicleKills=p.stats.vehicleKills||0};
for(const p of sim.people)init(p);
sim.creditKill=function(p,t,method='combat'){if(!p||!t||t._killCredited)return;t._killCredited=true;init(p);p.stats.kills++;if(t.kind==='zombie')p.stats.zombieKills++;else if(t.kind==='person')p.stats.humanKills++;if(method==='vehicle')p.stats.vehicleKills++;this.remember(p,'kill',`Matou ${t.kind==='zombie'?'uma figura hostil':'uma pessoa'} usando ${method==='vehicle'?'um veículo':'combate'}.`,7,['combat','kill'])};
sim.resolveAttack=function(p,id,style){const t=this.entityById(id);if(!t||!t.alive)return;init(p);const before=t.health,w=this.weaponStats(p);if(this.emitNoise)this.emitNoise(p.x,p.y,w.ammo?1.15:.3,w.ammo?'gunshot':'melee',p.id,w.ammo?'disparo de arma de fogo':'impacto de combate');oldAttack(p,id,style);const delta=Math.max(0,before-(t.health||0));if(delta>0){t.hitFlashUntil=performance.now()+190;this.effects.push({type:'impact_v06',x:t.x,y:t.y,life:8,amount:Math.round(delta)});if(!t.alive)this.creditKill(p,t,'combat')}};
sim.zombieWound=function(z,p){const first=this.recordZombieSight(p,z,'attack');for(const q of this.peopleGrid.near(p.x,p.y,230))if(q.alive&&q.id!==p.id&&this.canSee?.(q,z,230))this.recordZombieSight(q,z,'sight');const r=this.rng.next(),type=r<.18?'mordida':r<.5?'corte':'arranhão',chance=type==='mordida'?1:type==='corte'?.75:.5,severity=type==='mordida'?this.rng.range(.55,1):type==='corte'?this.rng.range(.3,.75):this.rng.range(.12,.42),infected=this.rng.chance(chance),bleeding=severity*(type==='mordida'?1.3:type==='corte'?1:.45);p.wounds.push({type,severity,infected,bleeding,minute:this.minute});p.pain=window.AZ.clamp(p.pain+severity*35,0,100);p.health-=severity*9;p.stress=window.AZ.clamp(p.stress+18,0,100);if(infected)p.infection=Math.max(p.infection,.015);this.remember(p,'wound',`Sofreu ${type}. Não sabe ainda quais serão as consequências da ferida.`,9,['wound','illness']);p.hitFlashUntil=performance.now()+260;this.effects.push({type:'wound_v06',x:p.x,y:p.y,life:10,amount:Math.round(severity*9)});if(this.emitNoise)this.emitNoise(p.x,p.y,.5,'struggle',p.id,'grito e luta corporal');return{type,infected,first}};
sim.resolveTalk=function(a,b,message,intent){if(this.emitNoise)this.emitNoise(a.x,a.y,.12,'voice',a.id,'voz humana');return oldTalk(a,b,message,intent)};
sim.advanceDrive=function(p,a,dt){oldDrive(p,a,dt);const v=p.vehicleId&&this.world.vehicleById(p.vehicleId);if(v&&this.emitNoise){if(!v._lastNoise||this.minute-v._lastNoise>1.2){v._lastNoise=this.minute;this.emitNoise(v.x,v.y,.7,'engine',p.id,'motor de veículo')}}for(const z of this.zombies){if(z.alive||z._killCredited)continue;if(v&&Math.hypot(z.x-v.x,z.y-v.y)<46)this.creditKill(p,z,'vehicle')}};
sim.updateZombie=function(z,dt){const near=this.peopleGrid.near(z.x,z.y,390).filter(p=>p.alive&&!p.vehicleId);if(!near.length&&this.noiseEvents?.length){let best=null,score=0;for(const n of this.noiseEvents){if(n.expires<=this.minute)continue;const d=Math.hypot(n.x-z.x,n.y-z.y),s=n.loudness*650-d;if(s>score){score=s;best=n}}if(best&&score>30)z.target={x:best.x,y:best.y,alive:true,noise:true}}return oldUpdateZombie(z,dt)};
const oldDrawPerson=renderer.drawPerson.bind(renderer),oldDrawZombie=renderer.drawZombie.bind(renderer);
renderer.drawPerson=function(p){oldDrawPerson(p);if((p.hitFlashUntil||0)>performance.now()){const c=this.ctx;c.save();c.globalAlpha=.65;c.fillStyle='#fff2e8';c.fillRect(p.x-7,p.y-11,14,24);c.restore()}};
renderer.drawZombie=function(z){oldDrawZombie(z);if((z.hitFlashUntil||0)>performance.now()){const c=this.ctx;c.save();c.globalAlpha=.7;c.fillStyle='#ffd4c7';c.fillRect(z.x-7,z.y-11,14,23);c.restore()}};
renderer.drawEffects=function(){const ctx=this.ctx;for(const e of sim.effects){if(e.type==='blood'){ctx.fillStyle=`rgba(130,28,28,${Math.min(.85,e.life/12)})`;for(let i=0;i<4;i++){const a=i*1.7+e.life*.1,r=3+i*2;ctx.fillRect(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,2+i%2,2+i%2)}}else if(e.type==='miss'){ctx.strokeStyle='rgba(235,235,215,.7)';ctx.beginPath();ctx.moveTo(e.x-7,e.y-7);ctx.lineTo(e.x+7,e.y+7);ctx.stroke()}else if(e.type==='impact_v06'||e.type==='wound_v06'||e.type==='hit'){const r=Math.max(3,13-e.life);ctx.strokeStyle=e.type==='wound_v06'?'rgba(220,70,55,.85)':'rgba(255,215,150,.9)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(e.x,e.y,r,0,Math.PI*2);ctx.stroke();if(e.amount){ctx.fillStyle='rgba(255,235,220,.9)';ctx.font='8px system-ui';ctx.textAlign='center';ctx.fillText(`-${e.amount}`,e.x,e.y-10)}}else{ctx.fillStyle='#d97b44';ctx.fillRect(e.x-4,e.y-4,8,8)}}};
})();
