'use strict';
(()=>{
const sim=window.sim,renderer=window.renderer,$=id=>document.getElementById(id);if(!sim||!renderer||!$('drawer'))return;
const version=document.querySelector('.drawerHead small');if(version)version.textContent='v0.6 · sandbox procedural';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const tabs=document.querySelector('.tabs');
if(tabs&&!document.querySelector('[data-tab="ranking"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='ranking';b.textContent='Kills';tabs.insertBefore(b,document.querySelector('[data-tab="worldtab"]'));b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('rankingPanel').classList.add('active');renderRanking()}}
if(!$('rankingPanel')){const sec=document.createElement('section');sec.className='panel';sec.id='rankingPanel';sec.innerHTML='<h3>Ranking de eliminações</h3><div id="killRanking"></div><p class="hint">Toque em uma pessoa para centralizar a câmera e abrir a inspeção.</p>';$('worldtabPanel').before(sec)}
const css=document.createElement('style');css.textContent='.rankRow{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:8px;align-items:center;width:100%;padding:9px;border:0;border-bottom:1px solid rgba(255,255,255,.07);background:transparent;color:inherit;text-align:left}.rankRow:active{background:rgba(255,255,255,.08)}.rankRow small{opacity:.55}';document.head.appendChild(css);
function renderRanking(){const root=$('killRanking');if(!root)return;const rows=sim.people.slice().sort((a,b)=>(b.stats?.kills||0)-(a.stats?.kills||0)||(b.stats?.zombieKills||0)-(a.stats?.zombieKills||0)).slice(0,50);root.innerHTML=rows.map((p,i)=>`<button class="rankRow" data-person="${esc(p.id)}"><b>#${i+1}</b><span>${esc(p.name)}<small>${p.alive?'vivo':'morto'} · ${p.type==='agent'?'agente IA':p.military?'militar':'NPC'}</small></span><b>${p.stats?.kills||0}<small>${p.stats?.zombieKills||0} ameaças · ${p.stats?.humanKills||0} humanos</small></b></button>`).join('');root.querySelectorAll('[data-person]').forEach(el=>el.onclick=()=>{const p=sim.people.find(x=>x.id===el.dataset.person);if(!p)return;sim.selected=p;renderer.centerOnSelected();window.dispatchEvent(new CustomEvent('az-selection',{detail:p}));document.querySelector('[data-tab="inspect"]')?.click()})}
setInterval(()=>{if(document.querySelector('[data-tab="ranking"]')?.classList.contains('active'))renderRanking()},900);
})();
